//! One v2 generation run: read the model, account for every declared element,
//! emit what is implemented.
//!
//! The run owns its whole pipeline — parsing, resolution, plans, emission and
//! the report. It reads the same model and the same declarations v1 does and
//! shares nothing else with it: no `Registry`, no fragment store, no resolver,
//! no emitter. That independence is the point of #719, and a dependency edge is
//! how it would be lost.

use std::path::{Path, PathBuf};

use prebindgen_flat::flat::{Flat, FlatBuilder};

use crate::{
    decl::{BindingDeclarations, ElementKind},
    outcome::{EngineError, Outcome, Skip},
    report::{sort_entries, Entry, Report, SourceIdentity, SCHEMA_VERSION},
};

/// The engine's name wherever a run identifies itself.
pub const PIPELINE: &str = "v2";

/// A finished v2 run: the model it read, what it generated, and the manifest.
///
/// Immutable. Every writer is a pure emission over it, so they can run in any
/// order, or not at all.
pub struct Generation {
    flat: Flat,
    report: Report,
}

impl std::fmt::Debug for Generation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Generation({})", self.report.summary())
    }
}

impl Generation {
    /// The model this run was planned over.
    pub fn flat(&self) -> &Flat {
        &self.flat
    }

    /// What was generated and what was not — see [`Report`].
    pub fn report(&self) -> &Report {
        &self.report
    }

    /// Write the generated Rust file.
    ///
    /// Stamped with the pipeline that produced it and the counts behind it, so
    /// a file included by mistake from the other engine's output root says so
    /// on its first line rather than by a link error. The file is always valid
    /// Rust: a consumer's `include!` compiles whether this run generated
    /// anything or not.
    pub fn write_rust(&self, out_path: impl AsRef<Path>) -> Result<PathBuf, EngineError> {
        let out_path = out_path.as_ref().to_path_buf();
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let counts = self.report.counts();
        let contents = format!(
            "// Generated by prebindgen {PIPELINE} ({} target) — do not edit.\n\
             // {} emitted, {} skipped, {} ignored; see the report beside this file.\n",
            self.report.target, counts.emitted, counts.skipped, counts.ignored
        );
        std::fs::write(&out_path, contents)?;
        Ok(out_path)
    }
}

/// Plan `declarations` over the model their `sources` parse into.
///
/// Every declared element leaves this with an outcome. Nothing is dropped for
/// being unimplemented and nothing is generated by another engine: an element
/// v2 cannot lower is a reported skip, and the run continues.
pub fn plan(
    declarations: &dyn BindingDeclarations,
    sources: FlatBuilder,
    declaring_crate: impl Into<String>,
) -> Result<Generation, EngineError> {
    let flat = sources.build()?;

    let declared = declarations.declared_elements();
    // A declaration is a statement of intent, so a declared item the source
    // never captured is an error and not a capability question — the same rule
    // v1 holds, and the reason `must_resolve` is stated per element.
    // Captured items live in one flat namespace, so this is one lookup and not
    // one per kind: a Kotlin `val` may be backed by a nullary function, and
    // asking the constant table for it would report a typo that is not there.
    let missing: Vec<_> = declared
        .iter()
        .filter(|element| element.must_resolve)
        .filter(|element| flat.element(element.rust_origin.as_str()).is_none())
        .map(|element| (element.id.clone(), element.rust_origin.clone()))
        .collect();
    if !missing.is_empty() {
        return Err(EngineError::DeclaredNotFound { entries: missing });
    }

    // One id, one element: the manifest is read by id, and a repeat would leave
    // one of the two entries unaccounted for.
    let mut seen = std::collections::HashSet::new();
    let mut repeated: Vec<_> = declared
        .iter()
        .filter(|element| !seen.insert(&element.id))
        .map(|element| element.id.clone())
        .collect();
    repeated.sort();
    repeated.dedup();
    if !repeated.is_empty() {
        return Err(EngineError::DuplicateElement { entries: repeated });
    }

    let mut elements: Vec<Entry> = declared
        .into_iter()
        .map(|element| {
            let skip = not_implemented(element.kind, &element.rust_origin);
            Entry {
                element,
                outcome: Outcome::Skipped(skip),
            }
        })
        .chain(
            declarations
                .ignored_elements()
                .into_iter()
                .map(|element| Entry {
                    element,
                    outcome: Outcome::Ignored,
                }),
        )
        .collect();
    sort_entries(&mut elements);

    let report = Report {
        pipeline: PIPELINE,
        target: declarations.target(),
        schema_version: SCHEMA_VERSION,
        source_identity: SourceIdentity {
            declaring_crate: declaring_crate.into(),
            sources: flat.source_modules().to_vec(),
            captured_items: flat.elements().count(),
        },
        elements,
    };
    Ok(Generation { flat, report })
}

/// The skip every element takes while v2 has no lowering for its kind.
///
/// One code per kind rather than one code for the whole engine: the report is
/// how the next capability is chosen, and "everything is unsupported" chooses
/// nothing.
fn not_implemented(kind: ElementKind, origin: &str) -> Skip {
    Skip::direct(
        format!("unsupported.{}.not_implemented", kind.as_str()),
        format!(
            "the v2 engine has no {} lowering yet",
            match kind {
                ElementKind::Function => "function",
                ElementKind::Type => "type representation",
                ElementKind::Const => "constant",
                ElementKind::Callback => "callback",
                ElementKind::Conversion => "conversion",
            }
        ),
        origin,
    )
}
