//! One finished v2 generation run: what was planned, what was emitted, and the
//! manifest that accounts for every declared element.
//!
//! The run owns its whole pipeline — parsing, resolution, plans, emission and
//! the report. It reads the same model and the same declarations v1 does and
//! shares nothing else with it: no `Registry`, no fragment store, no resolver,
//! no emitter. That independence is the point of #719, and a dependency edge is
//! how it would be lost. [`crate::generate`] is the entry point; this is its
//! result.

use std::path::{Path, PathBuf};

use prebindgen_flat::flat::Flat;

use crate::{decl::SourceKind, outcome::EngineError, report::Report};

/// The engine's name wherever a run identifies itself.
pub const PIPELINE: &str = "v2";

/// A finished v2 run: the model it read, what it generated, and the manifest.
///
/// Immutable. Every writer is a pure emission over it, so they can run in any
/// order, or not at all.
pub struct Generation<P = ()> {
    flat: Flat,
    report: Report,
    values: Vec<crate::plan::ValuePlan<P>>,
    functions: Vec<crate::plan::FunctionPlan<P>>,
    surfaces: Vec<crate::target::SurfaceSpec<P>>,
    primitives: Vec<crate::target::PrimitiveSpec<P>>,
    rust: String,
}

impl<P> std::fmt::Debug for Generation<P> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Generation({})", self.report.summary())
    }
}

impl<P> Generation<P> {
    /// A finished run over the plans it retained.
    pub(crate) fn new(
        flat: Flat,
        report: Report,
        values: Vec<crate::plan::ValuePlan<P>>,
        functions: Vec<crate::plan::FunctionPlan<P>>,
        surfaces: Vec<crate::target::SurfaceSpec<P>>,
        primitives: Vec<crate::target::PrimitiveSpec<P>>,
        rust: String,
    ) -> Self {
        Generation {
            flat,
            report,
            values,
            functions,
            surfaces,
            primitives,
            rust,
        }
    }

    /// The retained conversions, shared by every value that crosses the same
    /// way.
    pub fn values(&self) -> &[crate::plan::ValuePlan<P>] {
        &self.values
    }

    /// The retained native wrappers.
    pub fn functions(&self) -> &[crate::plan::FunctionPlan<P>] {
        &self.functions
    }

    /// The retained public declarations, which is what a target's own foreign
    /// writer renders from.
    pub fn surfaces(&self) -> &[crate::target::SurfaceSpec<P>] {
        &self.surfaces
    }

    /// The registered operations the wrappers apply.
    pub fn primitives(&self) -> &[crate::target::PrimitiveSpec<P>] {
        &self.primitives
    }

    /// The generated Rust, as it is written to disk.
    pub fn rust(&self) -> &str {
        &self.rust
    }

    /// The model this run was planned over.
    pub fn flat(&self) -> &Flat {
        &self.flat
    }

    /// What was generated and what was not — see [`Report`].
    pub fn report(&self) -> &Report {
        &self.report
    }

    /// Write the generated Rust file.
    ///
    /// Stamped with the pipeline that produced it and the counts behind it, so
    /// a file included by mistake from the other engine's output root says so
    /// on its first line rather than by a link error. The file is always valid
    /// Rust: a consumer's `include!` compiles whether this run generated
    /// anything or not.
    pub fn write_rust(&self, out_path: impl AsRef<Path>) -> Result<PathBuf, EngineError> {
        // A relative path is resolved against `OUT_DIR`, as v1 resolves one: a
        // build script that writes `"perftest.rs"` must not land a file in the
        // crate root under one engine and in `OUT_DIR` under the other.
        let out_path = out_path.as_ref();
        let out_path = if out_path.is_relative() {
            PathBuf::from(std::env::var("OUT_DIR").map_err(|_| {
                std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    "a relative output path needs OUT_DIR, which only a build script sets",
                )
            })?)
            .join(out_path)
        } else {
            out_path.to_path_buf()
        };
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let counts = self.report.counts();
        let contents = format!(
            "// Generated by prebindgen {PIPELINE} ({} target) — do not edit.\n\
             // {} emitted, {} skipped, {} ignored; see the report beside this file.\n{}",
            self.report.target, counts.emitted, counts.skipped, counts.ignored, self.rust
        );
        std::fs::write(&out_path, contents)?;
        Ok(out_path)
    }
}

/// Check declared elements against the model before anything is planned.
///
/// A declaration is a statement of intent, so a declared item the source never
/// captured is an error and not a capability question — the same rule v1 holds.
///
/// Each element says which of the three captured kinds its origin must name —
/// which is not always its own kind, since a Kotlin `val` may be backed by a
/// nullary function. Looking a function up among the constants reported a typo
/// that was not there; looking it up in the whole namespace let a
/// `.fun(fun!(x))` naming a captured `const x` through as a capability skip.
pub(crate) fn check_declarations(
    declared: &[crate::decl::DeclaredElement],
    flat: &Flat,
) -> Result<(), EngineError> {
    let missing: Vec<_> = declared
        .iter()
        .filter(|element| {
            let origin = element.rust_origin.as_str();
            match element.source {
                SourceKind::Function => flat.function(origin).is_none(),
                SourceKind::Type => flat.declared_type(origin).is_none(),
                SourceKind::Const => flat.constant(origin).is_none(),
                SourceKind::BindingLocal => false,
            }
        })
        .map(|element| {
            (
                element.id.clone(),
                element.source,
                element.rust_origin.clone(),
            )
        })
        .collect();
    if !missing.is_empty() {
        return Err(EngineError::DeclaredNotFound { entries: missing });
    }

    // One id, one element: the manifest is read by id, and a repeat would leave
    // one of the two entries unaccounted for.
    let mut seen = std::collections::HashSet::new();
    let mut repeated: Vec<_> = declared
        .iter()
        .filter(|element| !seen.insert(&element.id))
        .map(|element| element.id.clone())
        .collect();
    repeated.sort();
    repeated.dedup();
    if !repeated.is_empty() {
        return Err(EngineError::DuplicateElement { entries: repeated });
    }
    Ok(())
}
