/* Generated by cbindgen for perftest bindings */

#ifndef PERFTEST_H
#define PERFTEST_H

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct string_t {
  uint8_t _private[0];
} string_t;

typedef struct payload_t {
  uint64_t id;
  uint32_t seq;
  double value;
  bool flag;
  struct string_t *label;
} payload_t;

typedef struct closure_payload_t {
  void *context;
  void (*call)(const struct payload_t*, void*);
  void (*drop)(void*);
} closure_payload_t;

void string_drop(struct string_t *this_);

void payload_drop(struct payload_t *this_);

void payload_callback(struct closure_payload_t f);

struct payload_t payload_get(void);

void payload_put(const struct payload_t *p);

uintptr_t string_len(const struct string_t *s);

struct string_t *string_new(const char *s);

#endif  /* PERFTEST_H */
