[workspace]
members = [
    ".",
    "examples/ffi_binding",
    "examples/ffi_common",
]
resolver = "2"

[workspace.dependencies]
prebindgen = { path = "." }

[package]
name = "prebindgen"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
