[workspace]
members = [
    "prebindgen",
    "prebindgen-proc-macro",
    "examples/ffi_binding",
    "examples/ffi_common",
]
resolver = "2"

[workspace.dependencies]
prebindgen = { path = "prebindgen" }
prebindgen-proc-macro = { path = "prebindgen-proc-macro" }
