[package]
name = "prebindgen"
version = "0.1.0"
edition = "2024"

[features]
suppress-outdir-warning = []

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.8"
