[workspace]
members = [
    "prebindgen",
    "prebindgen-proc-macro",
    "examples/example-cbindgen",
    "examples/example-ffi",
]
resolver = "2"

[workspace.dependencies]
prebindgen = { path = "prebindgen" }
prebindgen-proc-macro = { path = "prebindgen-proc-macro" }
