//! The [`Transmute`] and [`Gravestone`] runtime traits for inline-opaque
//! by-value FFI types.
//!
//! Unlike the rest of `core`, these are *runtime* traits: they are implemented on
//! the opaque counterpart of an inline-by-value Rust type and called from the
//! `extern "C"` converters that [`crate::lang::Cbindgen`] emits for a
//! `value_opaque` declaration.
//!
//! An inline-opaque type is passed across the C ABI *by value* (no `Box`): the
//! Rust value's bytes live directly inside a `#[repr(C, align(_))]` opaque struct
//! of identical size/alignment. [`Transmute`] is the (autogenerated) glue that
//! moves a value between the two representations; [`Gravestone`] adds the
//! *logical* empty/moved-from state on top, which the user supplies.
//!
//! Because C "moves" by bitwise copy, a moved-from value still occupies the
//! caller's slot; a *gravestone* is the empty, safely-droppable state written
//! back into that slot after the live value is moved out, so a later destructor
//! call is a harmless no-op.

/// Safe view of an opaque FFI byte-struct as its size/alignment-matched Rust type.
///
/// The impl is **autogenerated** by [`crate::lang::Cbindgen`] for a `value_opaque`
/// pair (alongside a `const` size/alignment-equality assertion). Because it is
/// only ever emitted for asserted matched pairs, the conversions are sound and the
/// trait methods are exposed as **safe** — the `unsafe` is encapsulated in the
/// generated impl.
pub trait Transmute: Sized {
    /// The original Rust type whose bytes the opaque struct holds.
    type Rust;

    /// Move a Rust value into the opaque representation.
    fn from_rust(value: Self::Rust) -> Self;

    /// Move the Rust value back out of the opaque representation.
    fn into_rust(self) -> Self::Rust;

    /// Reinterpret the opaque storage as a shared reference to the Rust value.
    fn as_rust(&self) -> &Self::Rust;

    /// Reinterpret the opaque storage as a mutable reference to the Rust value.
    fn as_rust_mut(&mut self) -> &mut Self::Rust;
}

/// An inline-opaque value type with a representable *gravestone* (empty /
/// moved-from) state.
///
/// The user implements only the **logic** — what an empty value of the Rust type
/// is ([`Self::rust_gravestone`]) and how to detect it ([`Self::rust_is_gravestone`]).
/// The opaque-side [`Self::gravestone`] / [`Self::is_gravestone`] (the surface the
/// generated converters call) are provided automatically via [`Transmute`], so no
/// hand-written `unsafe`/transmute is needed.
pub trait Gravestone: Transmute {
    /// A freshly-constructed empty, safely-droppable value of the Rust type.
    fn rust_gravestone() -> Self::Rust;

    /// Whether a Rust value currently holds the gravestone (empty) state.
    ///
    /// For a sound `Option<Self>` niche this must be a state that **no live value
    /// ever holds** — otherwise a legitimate value resembling the gravestone is
    /// misread as `None`.
    fn rust_is_gravestone(rust: &Self::Rust) -> bool;

    /// The opaque gravestone: an empty value written into a source slot after its
    /// live value is moved out. Autoprovided from [`Self::rust_gravestone`].
    fn gravestone() -> Self {
        Self::from_rust(Self::rust_gravestone())
    }

    /// Whether `self` currently holds the gravestone state. Autoprovided from
    /// [`Self::rust_is_gravestone`].
    fn is_gravestone(&self) -> bool {
        Self::rust_is_gravestone(self.as_rust())
    }
}
