[package]
name = "ffi_binding"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
prebindgen = { workspace = true }
ffi_common = { path = "../ffi_common" }

[build-dependencies]
prebindgen = { workspace = true }
ffi_common = { path = "../ffi_common" }
serde_json = "1.0"