//! Which generation engine a build script runs.
//!
//! There are two: **v1**, the engine every adapter ships today, and **v2**, the
//! parallel engine of [#719](https://github.com/milyin/prebindgen/issues/719).
//! Both read the same declarations; a build script picks one, and the pick is
//! made once, at the final `.build()`, before either engine plans anything.
//!
//! Two things decide it, and they are deliberately different questions:
//!
//! * **Availability** is a compile-time fact — the adapter's optional `v2`
//!   Cargo feature. An environment variable cannot enable a dependency after
//!   compilation has started, so a v2 run needs `--features v2` on the Cargo
//!   command as well as the selector below.
//! * **Selection** is a build-time fact — `PREBINDGEN_PIPELINE=v1|v2`, read at
//!   dispatch. Unset means v1, *including* under `--all-features`: enabling the
//!   feature makes v2 available and never selects it.
//!
//! [`Pipeline::resolve`] is the one validator both routes go through — the
//! environment (`.build()`) and an explicit request (`.build_with(..)`).

/// The environment variable naming the engine to run.
pub const PIPELINE_ENV: &str = "PREBINDGEN_PIPELINE";

/// The engine a binding is generated by.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Pipeline {
    /// The engine every adapter ships today.
    V1,
    /// The parallel engine of #719: generates what it implements and reports
    /// the rest.
    V2,
}

impl Pipeline {
    /// The selector spelling — also the directory component pipeline-specific
    /// outputs are placed under.
    pub fn as_str(self) -> &'static str {
        match self {
            Pipeline::V1 => "v1",
            Pipeline::V2 => "v2",
        }
    }

    /// What `PREBINDGEN_PIPELINE` asks for: `None` when it is unset.
    ///
    /// Registers `cargo:rerun-if-env-changed` when called from a build script,
    /// so changing the selector rebuilds rather than leaving the previous
    /// engine's artifacts in place. An explicitly empty value is a
    /// configuration error, not "unset": it almost always means a wrapper
    /// script computed the value and got nothing.
    pub fn from_env() -> Result<Option<Pipeline>, PipelineError> {
        // Only a build script has an OUT_DIR, and only there does the line mean
        // anything — printed from a test it would be noise on stdout.
        if std::env::var_os("OUT_DIR").is_some() {
            println!("cargo:rerun-if-env-changed={PIPELINE_ENV}");
        }
        match std::env::var(PIPELINE_ENV) {
            Err(_) => Ok(None),
            Ok(value) => match value.as_str() {
                "v1" => Ok(Some(Pipeline::V1)),
                "v2" => Ok(Some(Pipeline::V2)),
                _ => Err(PipelineError::UnknownSelector { value }),
            },
        }
    }

    /// The engine to run, given what was asked for and what was compiled in.
    ///
    /// `requested` is `None` for the environment route with the selector unset,
    /// which is v1. `v2_available` is the adapter's `cfg!(feature = "v2")`.
    /// Requesting an unavailable engine fails here — before any generation, and
    /// never by falling back to the other engine.
    pub fn resolve(
        requested: Option<Pipeline>,
        v2_available: bool,
        facade_crate: &'static str,
    ) -> Result<Pipeline, PipelineError> {
        match requested.unwrap_or(Pipeline::V1) {
            Pipeline::V1 => Ok(Pipeline::V1),
            Pipeline::V2 if v2_available => Ok(Pipeline::V2),
            Pipeline::V2 => Err(PipelineError::Unavailable { facade_crate }),
        }
    }
}

impl std::fmt::Display for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A pipeline was asked for that cannot be run — reported before generation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PipelineError {
    /// `PREBINDGEN_PIPELINE` held something other than `v1` or `v2` (an empty
    /// value included).
    UnknownSelector { value: String },
    /// V2 was selected in a build that did not compile it.
    Unavailable { facade_crate: &'static str },
}

impl std::fmt::Display for PipelineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PipelineError::UnknownSelector { value } => write!(
                f,
                "{PIPELINE_ENV}=`{value}` is not a pipeline: set it to `v1` or `v2`, \
                 or leave it unset for `v1`"
            ),
            PipelineError::Unavailable { facade_crate } => write!(
                f,
                "{PIPELINE_ENV}=v2, but this build of `{facade_crate}` has no v2 engine: \
                 a Cargo feature cannot be turned on by an environment variable, so add \
                 `--features v2` to the cargo command (or enable `{facade_crate}`'s `v2` \
                 dependency feature). The v1 engine is never run in its place"
            ),
        }
    }
}

impl std::error::Error for PipelineError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unset_selects_v1_whether_or_not_v2_is_available() {
        for available in [false, true] {
            assert_eq!(
                Pipeline::resolve(None, available, "prebindgen-c"),
                Ok(Pipeline::V1)
            );
        }
    }

    #[test]
    fn an_explicit_request_needs_the_engine_to_be_compiled_in() {
        assert_eq!(
            Pipeline::resolve(Some(Pipeline::V2), true, "prebindgen-c"),
            Ok(Pipeline::V2)
        );
        assert_eq!(
            Pipeline::resolve(Some(Pipeline::V2), false, "prebindgen-c"),
            Err(PipelineError::Unavailable {
                facade_crate: "prebindgen-c"
            })
        );
        // V1 is always available, and asking for it is never refused.
        assert_eq!(
            Pipeline::resolve(Some(Pipeline::V1), false, "prebindgen-c"),
            Ok(Pipeline::V1)
        );
    }

    #[test]
    fn the_unavailable_message_says_how_to_make_it_available() {
        let message = PipelineError::Unavailable {
            facade_crate: "prebindgen-jni",
        }
        .to_string();
        assert!(message.contains("--features v2"), "{message}");
        assert!(message.contains("prebindgen-jni"), "{message}");
    }

    /// `from_env` reads process-wide state, so the tests that set it take turns.
    static ENV: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn with_selector<R>(value: Option<&str>, body: impl FnOnce() -> R) -> R {
        let _guard = ENV.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        match value {
            Some(value) => std::env::set_var(PIPELINE_ENV, value),
            None => std::env::remove_var(PIPELINE_ENV),
        }
        let result = body();
        std::env::remove_var(PIPELINE_ENV);
        result
    }

    #[test]
    fn the_selector_is_read_from_the_environment() {
        assert_eq!(with_selector(None, Pipeline::from_env), Ok(None));
        assert_eq!(
            with_selector(Some("v1"), Pipeline::from_env),
            Ok(Some(Pipeline::V1))
        );
        assert_eq!(
            with_selector(Some("v2"), Pipeline::from_env),
            Ok(Some(Pipeline::V2))
        );
    }

    #[test]
    fn an_unreadable_selector_is_a_configuration_error() {
        // An explicitly empty value is not "unset": it is a wrapper script that
        // computed the selector and got nothing.
        for value in ["", "V2", "2", "latest", " v2"] {
            assert_eq!(
                with_selector(Some(value), Pipeline::from_env),
                Err(PipelineError::UnknownSelector {
                    value: value.to_string()
                }),
                "`{value}` should not read as a pipeline"
            );
        }
    }

    #[test]
    fn every_availability_and_environment_combination() {
        // (selector, v2 compiled in) -> what runs.
        let cases: [(Option<&str>, bool, Result<Pipeline, ()>); 6] = [
            (None, false, Ok(Pipeline::V1)),
            // `--all-features` is this row: v2 available, selector unset, v1 runs.
            (None, true, Ok(Pipeline::V1)),
            (Some("v1"), false, Ok(Pipeline::V1)),
            (Some("v1"), true, Ok(Pipeline::V1)),
            (Some("v2"), true, Ok(Pipeline::V2)),
            (Some("v2"), false, Err(())),
        ];
        for (selector, available, expected) in cases {
            let resolved = with_selector(selector, || {
                Pipeline::resolve(Pipeline::from_env()?, available, "prebindgen-c")
            });
            match expected {
                Ok(pipeline) => assert_eq!(resolved, Ok(pipeline), "{selector:?}/{available}"),
                Err(()) => assert!(resolved.is_err(), "{selector:?}/{available} should fail"),
            }
        }
    }

    #[test]
    fn an_explicit_request_beats_the_environment_in_both_directions() {
        with_selector(Some("v2"), || {
            assert_eq!(
                Pipeline::resolve(Some(Pipeline::V1), true, "prebindgen-c"),
                Ok(Pipeline::V1)
            );
        });
        with_selector(Some("v1"), || {
            assert_eq!(
                Pipeline::resolve(Some(Pipeline::V2), true, "prebindgen-c"),
                Ok(Pipeline::V2)
            );
        });
    }

    #[test]
    fn an_unreadable_selector_names_what_it_held() {
        let message = PipelineError::UnknownSelector {
            value: String::new(),
        }
        .to_string();
        assert!(message.contains("`v1` or `v2`"), "{message}");
    }
}
