[package]
name = "shape-matrix"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
prebindgen = { workspace = true }
prebindgen-flat = { workspace = true }
prebindgen-registry = { workspace = true }
prebindgen-c = { workspace = true }
prebindgen-jni = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
tempfile = { workspace = true }
