[package]
name = "example-cbindgen"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
prebindgen = { workspace = true }
example-ffi = { path = "../example-ffi" }

[build-dependencies]
prebindgen = { workspace = true }
example-ffi = { path = "../example-ffi" }
serde_json = "1.0"
cbindgen = "0.29.0"