/* Generated by cbindgen for example_ffi bindings */

#ifndef EXAMPLE_FFI_H
#define EXAMPLE_FFI_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Foo {
  uint64_t x86_64_field;
  uint64_t aarch64_field;
} Foo;

typedef struct Bar {
  uint64_t aarch64_field;
} Bar;

bool another_test_function(void);

void void_function(int32_t _x);

int32_t test_function(int32_t _a, double _b);

void copy_foo(struct Foo *_dst, const struct Foo *_src);

#endif  /* EXAMPLE_FFI_H */
