[package]
name = "ffi_common"
version = "0.1.0"
edition = "2024"
build = "build.rs"
links = "ffi_common"

[dependencies]
prebindgen = { workspace = true }
prebindgen-proc-macro = { workspace = true }

[build-dependencies]
prebindgen = { workspace = true }