[package]
name = "prebindgen-project-root"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
description = "Utility to expose the workspace project root at build time"
documentation = { workspace = true }
keywords = { workspace = true }
categories = {workspace = true }
rust-version = { workspace = true }
readme = "README.md"

[lib]
name = "prebindgen_project_root"
path = "src/lib.rs"

[build-dependencies]
project-root = "0.2"
quote = "1"

[dependencies]
anyhow = "1"
toml_edit = { version = "0.22", features = ["serde"] }
pathdiff = "0.2"

[[bin]]
name = "cargo-prebindgen-project-root"
path = "src/main.rs"

[package.metadata.docs.rs]
all-features = true

[dev-dependencies]
assert_cmd = "2"
tempfile = { workspace = true }
