//! Writing the plan: every item through its generator, in order — the Rust
//! externs into one file, the Kotlin declarations into one file per package.

mod class;
mod function;
mod support;

use std::collections::BTreeMap;

use prebindgen_tools::RustFile;
use quote::quote;

use crate::{
    plan::{Item, Plan, Res},
    Generation,
};

/// What writing produces, as it accumulates.
pub(crate) struct Out {
    pub rust: RustFile,
    /// Kotlin declarations by package, in the order written.
    kt: BTreeMap<String, Vec<String>>,
    /// The `external fun` declarations of the native holder.
    pub externs: Vec<String>,
}

impl Out {
    pub(crate) fn kt(&mut self, pkg: &str, decl: String) {
        self.kt.entry(pkg.to_string()).or_default().push(decl);
    }
}

/// Write every item of the plan.
pub(crate) fn write(plan: &Plan) -> Res<Generation> {
    let mut out = Out {
        rust: RustFile::new(),
        kt: BTreeMap::new(),
        externs: Vec::new(),
    };
    out.rust.push(rust_prelude(plan));
    out.kt(&plan.base_pkg, support::PRELUDE.to_string());
    for item in &plan.items {
        match item {
            Item::Class {
                class,
                methods,
                ctors,
            } => class::class(plan, &mut out, class, methods, ctors)?,
            Item::Function { pkg, binding } => {
                let w = function::function(plan, &mut out, binding)?;
                out.kt(pkg, w.text);
            }
            Item::Constant { pkg, name, binding } => {
                class::constant(plan, &mut out, pkg, name, binding)?
            }
        }
    }
    for s in &plan.supports {
        let (pkg, text) = support::support(plan, s)?;
        out.kt(&pkg, text);
    }
    let holder = harness(plan, &out.externs);
    out.kt(&plan.base_pkg, holder);
    out.rust.guards(plan.flat);
    let kotlin = out
        .kt
        .into_iter()
        .map(|(pkg, decls)| {
            let text = format!(
                "// Auto-generated by prebindgen-jni — do not edit by hand.\n@file:Suppress(\"RedundantVisibilityModifier\", \"unused\", \"UNCHECKED_CAST\", \"FunctionName\", \"ClassName\", \"PropertyName\", \"LocalVariableName\", \"RemoveRedundantQualifierName\")\n\npackage {pkg}\n\n{}",
                decls.join("\n")
            );
            (pkg, text)
        })
        .collect();
    Ok(Generation {
        rust: out.rust,
        kotlin,
    })
}

/// The object holding the `external fun` declarations.
fn harness(plan: &Plan, externs: &[String]) -> String {
    let init = plan
        .native_init
        .as_ref()
        .map(|s| format!("    init {{\n        {s}\n    }}\n\n"))
        .unwrap_or_default();
    format!(
        "internal object {} {{\n{init}{}\n}}\n",
        plan.harness,
        externs.join("\n\n")
    )
}

/// The Rust side's shared helper: reporting a binding error to Kotlin.
fn rust_prelude(plan: &Plan) -> proc_macro2::TokenStream {
    let je = format!("{}/JniErrorHandler", plan.base_pkg.replace('.', "/"));
    quote! {
        /// Report a binding error to the Kotlin error sink, unless a
        /// Kotlin exception is already pending.
        #[allow(dead_code)]
        fn __jni_signal(
            env: &mut ::prebindgen_jni_runtime::jni::JNIEnv,
            sink: &::prebindgen_jni_runtime::jni::objects::JObject,
            msg: &str,
        ) {
            static __M: ::prebindgen_jni_runtime::CachedIfaceMethod =
                ::prebindgen_jni_runtime::CachedIfaceMethod::new();
            if env.exception_check().unwrap_or(false) {
                return;
            }
            let __s = match env.new_string(msg) {
                ::core::result::Result::Ok(s) => s,
                ::core::result::Result::Err(_) => return,
            };
            let _ = __M.call_object(
                env,
                #je,
                "run",
                "(Ljava/lang/String;)Ljava/lang/Object;",
                sink,
                &[::prebindgen_jni_runtime::jni::sys::jvalue { l: __s.as_raw() }],
            );
        }
    }
}

/// JNI's escaping of one name component: `_` → `_1`, `;` → `_2`, `[` →
/// `_3`, anything outside ASCII alphanumerics → `_0xxxx`.
fn jni_escape(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '_' => out.push_str("_1"),
            ';' => out.push_str("_2"),
            '[' => out.push_str("_3"),
            c if c.is_ascii_alphanumeric() => out.push(c),
            c => {
                let mut buf = [0u16; 2];
                for u in c.encode_utf16(&mut buf) {
                    out.push_str(&format!("_0{u:04x}"));
                }
            }
        }
    }
    out
}

/// The JNI symbol of a native method: `Java_<class>_<method>`.
pub(crate) fn jni_symbol(class_fqn: &str, method: &str) -> String {
    let class = class_fqn
        .split('.')
        .map(jni_escape)
        .collect::<Vec<_>>()
        .join("_");
    format!("Java_{class}_{}", jni_escape(method))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn symbols_escape_underscores() {
        assert_eq!(
            jni_symbol("io.prebindgen.covertest.esc_pkg.Esc_Probe", "freePtr"),
            "Java_io_prebindgen_covertest_esc_1pkg_Esc_1Probe_freePtr"
        );
        assert_eq!(
            jni_symbol("io.x.CovNative", "escape_probe_value"),
            "Java_io_x_CovNative_escape_1probe_1value"
        );
    }
}
