/* Generated by cbindgen for example_flat bindings */

#ifndef EXAMPLE_FLAT_H
#define EXAMPLE_FLAT_H

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum operation_t {
  Add = 0,
  Sub = 1,
  Mul = 2,
  Div = 3,
} operation_t;

typedef struct calculator_t {
  uint8_t _private[0];
} calculator_t;

typedef struct closure_calculator_t {
  void *context;
  void (*call)(const struct calculator_t*, void*);
  void (*drop)(void*);
} closure_calculator_t;

extern void *malloc(uintptr_t size);

extern void free(void *ptr);

void example_free(void *p);

void calculator_drop(struct calculator_t *this_);

bool calculator_apply(struct calculator_t *c,
                      enum operation_t op,
                      double operand,
                      double *out,
                      char **e);

uint64_t calculator_get_count(const struct calculator_t *c);

double *calculator_get_history(const struct calculator_t *c, uintptr_t *len);

double calculator_get_value(const struct calculator_t *c);

void calculator_inspect(const struct calculator_t *c, struct closure_calculator_t f);

bool calculator_is(const struct calculator_t *c, double value);

struct calculator_t *calculator_new(void);

struct calculator_t *calculator_new_clone(const struct calculator_t *c);

struct calculator_t *calculator_new_from_str(const char *s, char **e);

char *calculator_to_string(const struct calculator_t *c);

#endif  /* EXAMPLE_FLAT_H */
