/* Generated by cbindgen for example_flat bindings */

#ifndef EXAMPLE_FLAT_H
#define EXAMPLE_FLAT_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum operation_t {
  Add = 0,
  Sub = 1,
  Mul = 2,
  Div = 3,
} operation_t;

typedef enum grade_t {
  Low = 1,
  High = 2,
} grade_t;

typedef enum inside_foo_t {
  DouddleDee = 14,
  DouddleDum = 88,
} inside_foo_t;

typedef struct calculator_t {
  uint8_t _private[0];
} calculator_t;

typedef enum shape_t_Tag {
  Empty,
  Circle,
  Rect,
  Labeled,
} shape_t_Tag;

typedef struct Rect_Body {
  double width;
  double height;
} Rect_Body;

typedef struct Labeled_Body {
  char *_0;
  enum operation_t _1;
} Labeled_Body;

typedef struct shape_t {
  shape_t_Tag tag;
  union {
    struct {
      double circle;
    };
    Rect_Body rect;
    Labeled_Body labeled;
  };
} shape_t;

typedef struct caption_t {
  uint64_t id;
  char *text;
  bool emphatic;
} caption_t;

typedef struct drawing_t {
  uint64_t id;
  struct shape_t shape;
} drawing_t;

typedef enum note_t_Tag {
  Silent,
  Titled,
  After,
  Flagged,
  Sketched,
} note_t_Tag;

typedef struct note_t {
  note_t_Tag tag;
  union {
    struct {
      struct caption_t titled;
    };
    struct {
      uint64_t after;
    };
    struct {
      bool flagged;
    };
    struct {
      struct drawing_t sketched;
    };
  };
} note_t;

typedef struct closure_value_t {
  void *context;
  void (*call)(double, void*);
  void (*drop)(void*);
} closure_value_t;

typedef struct closure_maybe_grade_t {
  void *context;
  void (*call)(bool, enum grade_t, void*);
  void (*drop)(void*);
} closure_maybe_grade_t;

typedef struct closure_history_batch_t {
  void *context;
  void (*call)(double*, uintptr_t, void*);
  void (*drop)(void*);
} closure_history_batch_t;

typedef struct closure_maybe_value_t {
  void *context;
  void (*call)(bool, double, void*);
  void (*drop)(void*);
} closure_maybe_value_t;

typedef struct foo_t {
  uint64_t id;
  uint64_t aarch64_field;
  uint64_t stable_field;
} foo_t;

extern void *malloc(uintptr_t size);

extern void free(void *ptr);

void example_free(void *p);

void calculator_drop(struct calculator_t *this_);

void shape_drop(struct shape_t *this_);

void note_drop(struct note_t *this_);

bool calculator_absorb(struct calculator_t *a, const struct calculator_t *b, double *out, char **e);

bool calculator_apply(struct calculator_t *c,
                      enum operation_t op,
                      double operand,
                      double *out,
                      char **e);

void calculator_for_each(const struct calculator_t *c, struct closure_value_t f);

uint64_t calculator_get_count(const struct calculator_t *c);

double *calculator_get_history(const struct calculator_t *c, uintptr_t *len);

double calculator_get_value(const struct calculator_t *c);

void calculator_grade_or_none(const struct calculator_t *c, struct closure_maybe_grade_t f);

void calculator_history_batch(const struct calculator_t *c, struct closure_history_batch_t f);

bool calculator_is(const struct calculator_t *c, double value);

void calculator_last_or_none(const struct calculator_t *c, struct closure_maybe_value_t f);

struct calculator_t *calculator_merge(struct calculator_t *a, struct calculator_t *b, char **e);

struct calculator_t *calculator_new(void);

struct calculator_t *calculator_new_clone(const struct calculator_t *c);

struct calculator_t *calculator_new_from_str(const char *s, char **e);

char *calculator_to_string(const struct calculator_t *c);

struct caption_t caption_new(uint64_t id, const char *text, bool emphatic);

struct shape_t drawing_get_shape(struct drawing_t d);

struct drawing_t drawing_new(uint64_t id, struct shape_t shape);

uint64_t foo_get_id(struct foo_t f);

struct foo_t foo_new(uint64_t id);

enum inside_foo_t inside_foo_default(void);

int32_t inside_foo_value(enum inside_foo_t x);

bool note_emphatic(struct note_t n);

struct note_t note_new_after(uint64_t millis);

struct note_t note_new_flagged(bool flag);

struct note_t note_new_silent(void);

struct note_t note_new_sketched(uint64_t id, const char *label);

struct note_t note_new_titled(uint64_t id, const char *text, bool emphatic);

uint64_t note_value(struct note_t n);

double shape_area(struct shape_t s);

char *shape_get_label(struct shape_t s);

struct shape_t shape_new_circle(double radius);

struct shape_t shape_new_empty(void);

struct shape_t shape_new_labeled(const char *label, enum operation_t op);

struct shape_t shape_new_rect(double width, double height);

bool shape_try_area(struct shape_t s, double *out, char **e);

#endif  /* EXAMPLE_FLAT_H */
