[package]
name = "prebindgen"
version = "0.1.0"
edition = "2024"
description = "Split FFI definitions and actual FFI export to static/cdylib to separate crates"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.0"
