[package]
name = "prebindgen"
version = "0.1.0"
edition = "2024"
description = "Separate FFI implementation and language-specific binding into different crates"
license = "MIT OR Apache-2.0"
authors = ["Michael Ilyin <milyin@gmail.com>"]
repository = "https://github.com/milyin/prebindgen"
documentation = "https://docs.rs/prebindgen"
readme = "../README.md"
keywords = ["ffi", "bindings", "cbindgen", "csbindgen", "cross-platform"]
categories = ["development-tools", "external-ffi-bindings"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
regex = "1.0"
prettyplease = "0.2"
roxygen = "1.0.4"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.0"
