[package]
name = "tests-integration"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
prebindgen = { path = ".." }
prebindgen-proc-macro = { path = "../prebindgen-proc-macro" }
serde_json = "1.0"

[[bin]]
name = "test_structures"
path = "src/test_structures.rs"
