//! `KotlinExt` impl for [`JniGen`].
//!
//! [`JniGen::write_kotlin`] is the single entry point for every Kotlin
//! file the JNI back-end emits. Each per-kind emitter builds in-memory
//! `KotlinFile` *fragments*:
//!   * the shared `NativeHandle` base + `ZException` + lock helpers (root
//!     package, e.g. `io.zenoh.jni`).
//!   * one typed-handle class per `ptr_class` entry without
//!     `.suppress_kotlin_code()`.
//!   * one enum / data / `@JvmInline value` class per declaration.
//!   * one top-level free-function bucket per `package()` context.
//!   * the centralized `external fun` holder (`JNINative`). (`impl Fn(...)`
//!     params surface as typed Kotlin lambdas on the wrapper tier and erased
//!     `Any` here — no fun-interface files are generated.)
//!
//! The fragments are then MERGED by [`merge_package_files`] so every
//! Java/Kotlin package collapses to a SINGLE `.kt` file — named after the
//! package's last segment (`io.zenoh.jni.config` → `config.kt`) — that holds
//! all of that package's classes, enums, value-classes and free functions.
//!
//! Every `#[prebindgen]` function must be assigned a Kotlin home via
//! `.method(...)` on either a typed-handle / data-class / enum config
//! or on `package(...)`. Undeclared functions are skipped (see
//! `Registry::scan_declared` warnings). There is no "orphan" bucket.
//!
//! Each merged file is written via [`KotlinFile::write`], which translates
//! `package` into a sub-path under `kotlin_root`.

use super::*;

/// Declaration of one auto-generated typed `NativeHandle` subclass.
///
/// Consumed by [`JniGen::write_typed_handles`] (and forwarded to
/// [`JniGen::write_jni_wrappers`] so the same promotion list can carve
/// the matching skip-list). Each entry says "this Kotlin class is the
/// home for the named `#[prebindgen]` functions"; everything else stays
/// in the catch-all `JNIWrappers` object.
#[derive(Clone, Copy)]
pub(crate) struct TypedHandle<'a> {
    /// Short Rust name shown in the class doc comment (e.g. `"Publisher"`).
    /// Pure documentation, doesn't have to match anything in the Registry.
    pub rust_doc: &'a str,
    /// Package-qualified Kotlin class name (e.g.
    /// `"io.zenoh.jni.JNIPublisher"`).
    pub kotlin_fqn: &'a str,
}

impl JniGen {
    /// Unified Kotlin emission — single public entry point. Each per-kind
    /// emitter builds in-memory `KotlinFile` fragments; they are then merged
    /// by [`merge_package_files`] into one file per package and written under
    /// `kotlin_root`. Reads all configuration (typed-handle methods, Kotlin
    /// type names) from internal state set during the builder phase. Returns
    /// every path written (one per non-empty package).
    pub fn write_kotlin(
        &self,
        registry: &Registry<KotlinMeta>,
        kotlin_root: &Path,
    ) -> Result<Vec<PathBuf>, WriteKotlinError> {
        // Each emitter produces in-memory `KotlinFile` fragments (one per class
        // / enum / value-class / function-bucket). They are then MERGED so that
        // every Java/Kotlin package collapses to a single `.kt` file — named
        // after the package's last segment — holding all of that package's
        // classes, enums, value-classes and free functions.
        let mut fragments: Vec<KotlinFile> = Vec::new();
        fragments.push(self.write_native_handle());
        fragments.extend(self.write_enum_classes(registry)?);
        fragments.extend(self.write_data_classes(registry));
        fragments.extend(self.write_value_blobs()?);

        // Build the borrowed `TypedHandle<'_>` view from internal config.
        let owned = self.collect_typed_handles();
        let typed_handles: Vec<TypedHandle<'_>> = owned
            .iter()
            .map(|h| TypedHandle {
                rust_doc: &h.rust_doc,
                kotlin_fqn: &h.kotlin_fqn,
            })
            .collect();
        fragments.extend(self.write_typed_handles(&typed_handles));
        for (subpackage, pkg_cfg) in &self.packages {
            if pkg_cfg.functions.is_empty() {
                continue;
            }
            fragments.push(self.write_jni_package(registry, subpackage, pkg_cfg));
        }
        fragments.push(self.write_jni_native(registry));

        let mut written = Vec::new();
        for file in merge_package_files(fragments)? {
            written.push(file.write(kotlin_root)?);
        }
        Ok(written)
    }

    /// Emit `NativeHandle.kt` — the shared base class every typed handle
    /// extends, plus the `withSortedHandleLocks` helper that the generated
    /// wrappers use to acquire any number of handle monitors in one
    /// pointer-sorted, deadlock-safe pass.
    pub(crate) fn write_native_handle(&self) -> KotlinFile {
        let mut s = String::new();
        s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
        if !self.package.is_empty() {
            s.push_str(&format!("package {}\n\n", self.package));
        }
        s.push_str(
            "/** Base class for every typed native handle: owns the raw `Box<T>` pointer\n\
            \x20*  slot and its monitor. Subclasses add their type-specific `close()` /\n\
            \x20*  `take()` / `freePtr`. */\n\
            public abstract class NativeHandle(initialPtr: Long) : AutoCloseable {\n\
            \x20   @Volatile internal var ptr: Long = initialPtr\n\
            \x20   public fun peek(): Long = ptr\n\
            \x20   public fun isClosed(): Boolean = ptr == 0L\n\
            }\n\n",
        );
        // The N-ary locking helper is only referenced when wrappers are
        // emitted with locking on; skip it under `handle_locks(false)` so it
        // doesn't surface as an unused-`internal fun` warning.
        if self.emit_handle_locks {
            s.push_str(
                "/** Acquire every handle's monitor in one global order (sorted by raw\n\
                \x20*  pointer) so concurrent calls touching the same handles can't deadlock,\n\
                \x20*  then run [body]. Closed handles (`ptr == 0`) are still locked; callers\n\
                \x20*  re-read and null-check each pointer inside [body]. Scales to any arity. */\n\
                internal fun <R> withSortedHandleLocks(handles: List<NativeHandle>, body: () -> R): R {\n\
                \x20   val sorted = handles.sortedBy { it.ptr }\n\
                \x20   fun rec(i: Int): R = if (i == sorted.size) body() else synchronized(sorted[i]) { rec(i + 1) }\n\
                \x20   return rec(0)\n\
                }\n",
            );
            // Allocation-free fixed-arity overloads for the common cases (1–3
            // statically-known, non-null handles). `inline` folds both the
            // helper and [body] into the call site — no `ArrayList`, no
            // `sortedBy`, no recursion, no lambda object. The ordering key is
            // `ptr` ascending, IDENTICAL to the `List` overload above, so the
            // global lock order is consistent whichever overload a wrapper
            // uses — deadlock-freedom is preserved even across paths.
            s.push_str(
                "/** Allocation-free single-handle lock (one monitor, nothing to order). */\n\
                internal inline fun <R> withSortedHandleLocks(a: NativeHandle, body: () -> R): R =\n\
                \x20   synchronized(a) { body() }\n\
                /** Allocation-free two-handle lock: order by `ptr` then nest monitors. */\n\
                internal inline fun <R> withSortedHandleLocks(\n\
                \x20   a: NativeHandle,\n\
                \x20   b: NativeHandle,\n\
                \x20   body: () -> R,\n\
                ): R {\n\
                \x20   val first: NativeHandle\n\
                \x20   val second: NativeHandle\n\
                \x20   if (a.ptr <= b.ptr) { first = a; second = b } else { first = b; second = a }\n\
                \x20   return synchronized(first) { synchronized(second) { body() } }\n\
                }\n\
                /** Allocation-free three-handle lock: 3-compare sorting network, then nest. */\n\
                internal inline fun <R> withSortedHandleLocks(\n\
                \x20   a: NativeHandle,\n\
                \x20   b: NativeHandle,\n\
                \x20   c: NativeHandle,\n\
                \x20   body: () -> R,\n\
                ): R {\n\
                \x20   var x = a\n\
                \x20   var y = b\n\
                \x20   var z = c\n\
                \x20   if (x.ptr > y.ptr) { val t = x; x = y; y = t }\n\
                \x20   if (y.ptr > z.ptr) { val t = y; y = z; z = t }\n\
                \x20   if (x.ptr > y.ptr) { val t = x; x = y; y = t }\n\
                \x20   return synchronized(x) { synchronized(y) { synchronized(z) { body() } } }\n\
                }\n",
            );
        }
        // Error channel: every generated wrapper takes a trailing **error
        // callback** `onError: (je: String?, ze…) -> R`. On a native error the
        // Rust side invokes a capture (no JVM throw on the Rust side); the
        // wrapper calls `onError` after the native call returns. The callback has
        // a **default** that throws `ZException` (below) — so callers that don't
        // care still get an exception, while any caller can pass its own handler
        // (e.g. building a domain object, or throwing its own type).
        s.push_str(
            "\n/** Default error raised by a generated wrapper's `onError` when the\n\
            \x20*  caller doesn't supply a handler. `message` is the binding error\n\
            \x20*  (`je`) or the library error string (`ze`). */\n\
            public class ZException(message: String?) : RuntimeException(message)\n",
        );
        KotlinFile {
            contents: s,
            package: self.package.clone(),
            class_name: "NativeHandle".to_string(),
        }
    }

    /// Emit one `@JvmInline value class <Name>(val bytes: ByteArray)` per
    /// declared `value_blob` type. The class is the typed wrapper level; it is
    /// erased to its `ByteArray` field at the JVM/ABI level, so the `JNINative`
    /// extern (and the wire) stays `ByteArray` while wrappers speak the typed
    /// class. The single field name `bytes` matches `value_projection_field`.
    pub(crate) fn write_value_blobs(&self) -> Result<Vec<KotlinFile>, WriteKotlinError> {
        let mut written = Vec::new();
        // Deterministic order by canonical Rust type-key (the `types` map is a
        // HashMap, so iterate sorted keys rather than raw map order).
        let mut keys: Vec<&TypeKey> = self.types.keys().collect();
        keys.sort_by(|a, b| a.as_str().cmp(b.as_str()));
        for key in keys {
            let cfg = &self.types[key];
            if !cfg.value_blob {
                continue;
            }
            let fqn = cfg.kotlin_name.clone().ok_or_else(|| {
                WriteKotlinError::Other(format!("value_blob `{}` has no Kotlin FQN", key.as_str()))
            })?;
            let (package, class_name) = match fqn.rsplit_once('.') {
                Some((p, c)) => (p.to_string(), c.to_string()),
                None => (String::new(), fqn.clone()),
            };
            let mut s = String::new();
            s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
            if !package.is_empty() {
                s.push_str(&format!("package {}\n\n", package));
            }
            s.push_str(&format!(
                "/** Typed by-value wrapper for the native Rust `{}` (a `Copy` blob carried\n\
                \x20*  as its raw bytes; `@JvmInline`-erased to `ByteArray` at the JNI boundary). */\n\
                @JvmInline\n\
                public value class {}(public val bytes: ByteArray)\n",
                key.as_str(),
                class_name,
            ));
            let file = KotlinFile {
                contents: s,
                package,
                class_name,
            };
            written.push(file);
        }
        Ok(written)
    }

    /// Build the `TypedHandle` slice from internal `types` config.
    /// Iterates entries where `opaque.is_some()` and emits one
    /// `TypedHandle` per opaque-handle registration. Stable order by
    /// canonical Rust type-key — keeps generated output deterministic.
    fn collect_typed_handles(&self) -> Vec<OwnedTypedHandle> {
        let mut handles: Vec<OwnedTypedHandle> = Vec::new();
        let mut keys: Vec<&TypeKey> = self.types.keys().collect();
        keys.sort_by(|a, b| a.as_str().cmp(b.as_str()));
        for key in keys {
            let cfg = &self.types[key];
            let Some(opaque) = &cfg.opaque else { continue };
            if opaque.suppress_kotlin_code {
                continue;
            }
            let Some(kotlin_fqn) = &cfg.kotlin_name else {
                continue;
            };
            // rust_doc — short last-segment of the Rust type key (best
            // effort; only used in the generated doc comment).
            let rust_doc = key
                .as_str()
                .split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                .find(|s| !s.is_empty())
                .unwrap_or(key.as_str())
                .to_string();
            handles.push(OwnedTypedHandle {
                rust_doc,
                kotlin_fqn: kotlin_fqn.clone(),
            });
        }
        handles
    }
}

/// Owned counterpart of [`TypedHandle`] — used internally so the
/// `collect_typed_handles` helper doesn't have to hand out borrows of
/// `self.types`.
pub(crate) struct OwnedTypedHandle {
    pub rust_doc: String,
    pub kotlin_fqn: String,
}

impl JniGen {
    /// Emit one Kotlin `enum class` file per `enum_class`-declared type
    /// (skipping any flagged with `.suppress_kotlin_code()`). Variants
    /// render in declaration order using SCREAMING_SNAKE_CASE names; the
    /// constructor stores the Rust discriminant value (or the ordinal as
    /// a fallback when the discriminant isn't a bare integer literal).
    /// A `fromInt(value: Int)` companion mirrors the `Priority.fromInt`
    /// shape that hand-written enums use today, so adapter code stays
    /// uniform.
    pub(crate) fn write_enum_classes(
        &self,
        registry: &Registry<KotlinMeta>,
    ) -> Result<Vec<KotlinFile>, WriteKotlinError> {
        let mut written = Vec::new();
        // Deterministic order by canonical Rust type-key.
        let mut keys: Vec<&TypeKey> = self.types.keys().collect();
        keys.sort_by(|a, b| a.as_str().cmp(b.as_str()));
        for key in keys {
            let cfg = &self.types[key];
            let Some(enum_cfg) = &cfg.enum_cfg else {
                continue;
            };
            if enum_cfg.suppress_kotlin_code {
                continue;
            }
            let Some(kotlin_fqn) = &cfg.kotlin_name else {
                continue;
            };
            // Look up the syn::ItemEnum by the type-key's bare ident.
            let ty = key.to_type();
            let Some(ident) = (if let syn::Type::Path(tp) = &ty {
                tp.path.segments.last().map(|s| s.ident.clone())
            } else {
                None
            }) else {
                continue;
            };
            let Some((item_enum, _)) = registry.enums.get(&ident) else {
                continue;
            };
            let (package, class_name) = match kotlin_fqn.rsplit_once('.') {
                Some((p, c)) => (p.to_string(), c.to_string()),
                None => (String::new(), kotlin_fqn.clone()),
            };
            let file = KotlinFile {
                contents: render_enum_source(&package, &class_name, item_enum),
                package,
                class_name,
            };
            written.push(file);
        }
        Ok(written)
    }

    /// Build one Kotlin `data class` fragment per `data_class`-declared
    /// struct. Uses resolved converter metadata to derive Kotlin field
    /// types, so wrappers and data-class declarations stay in sync. A
    /// compatibility-alias fragment is appended when any data class is
    /// renamed relative to its Rust ident.
    pub(crate) fn write_data_classes(&self, registry: &Registry<KotlinMeta>) -> Vec<KotlinFile> {
        let mut written = Vec::new();
        let mut aliases: Vec<(String, String)> = Vec::new();
        let mut keys: Vec<&TypeKey> = self.types.keys().collect();
        keys.sort_by(|a, b| a.as_str().cmp(b.as_str()));

        for key in keys {
            let cfg = &self.types[key];
            // Opaque handles, enums and `value_blob` (`@JvmInline value`)
            // types each have their own emitter; only plain structs become
            // data classes here.
            if cfg.opaque.is_some() || cfg.enum_cfg.is_some() || cfg.value_blob {
                continue;
            }
            let Some(kotlin_fqn) = &cfg.kotlin_name else {
                continue;
            };

            let ty = key.to_type();
            let Some(ident) = (if let syn::Type::Path(tp) = &ty {
                tp.path.segments.last().map(|s| s.ident.clone())
            } else {
                None
            }) else {
                continue;
            };
            let Some((item_struct, _)) = registry.structs.get(&ident) else {
                continue;
            };

            let (package, class_name) = match kotlin_fqn.rsplit_once('.') {
                Some((p, c)) => (p.to_string(), c.to_string()),
                None => (String::new(), kotlin_fqn.clone()),
            };
            if item_struct.ident.to_string() != class_name {
                aliases.push((item_struct.ident.to_string(), class_name.clone()));
            }
            written.push(KotlinFile {
                contents: render_data_class_source(
                    self,
                    &package,
                    &class_name,
                    item_struct,
                    registry,
                ),
                package,
                class_name,
            });
        }

        if !aliases.is_empty() {
            written.push(KotlinFile {
                contents: render_data_class_aliases_source(&self.package, &aliases),
                package: self.package.clone(),
                class_name: "JNIDataClassAliases".to_string(),
            });
        }

        written
    }

    /// Build the package-level wrapper fragment for the given subpackage.
    /// One top-level safe wrapper per `MethodEntry` in `pkg_cfg.functions`.
    /// Wrappers delegate to the centralized Native object (see
    /// [`Self::write_jni_native`]). Opaque-handle parameters become
    /// `NativeHandle`; the wrapper body nests `withPtr` / `consume` per
    /// the type-conversion rule. Non-opaque parameters pass through with
    /// the Kotlin type from `kotlin_types`. Opaque-handle return values
    /// are wrapped in `NativeHandle(...)` before return.
    pub(crate) fn write_jni_package(
        &self,
        registry: &Registry<KotlinMeta>,
        subpackage: &str,
        pkg_cfg: &crate::api::lang::jnigen::jni::PackageConfig,
    ) -> KotlinFile {
        let class_name = self.jni_package_class_name(subpackage);
        let package = if self.package.is_empty() {
            subpackage.to_string()
        } else if subpackage.is_empty() {
            self.package.clone()
        } else {
            format!("{}.{}", self.package, subpackage)
        };
        let contents = render_jni_package_source(self, registry, &pkg_cfg.functions, &package);
        KotlinFile {
            package,
            class_name,
            contents,
        }
    }

    /// Emit the centralized Native-object Kotlin file under `output_dir`
    /// (class name from [`JniGen::jni_native_class_name`]). Holds one
    /// `external fun` per `#[prebindgen]` function — names mangled via
    /// `kotlin_fun_name_mangle`, parameter and return types rendered at
    /// the JNI **wire** level so the declarations match the Rust extern
    /// symbols generated under
    /// `Java_<package>_<jni_native_class>_<name>`. Loading the native
    /// library is the wrapper layer's responsibility — the auto-generated
    /// holder stays free of any reference to higher-layer types so that
    /// `io.zenoh.jni.*` doesn't depend on `io.zenoh.*`. Trigger
    /// `System.load` / `System.loadLibrary` from wrapper entry points
    /// (e.g. via a `companion object { init { ZenohLoad } }` block) so
    /// the lib is in place before any extern call.
    pub(crate) fn write_jni_native(&self, registry: &Registry<KotlinMeta>) -> KotlinFile {
        let class_name = self.jni_native_class_name();
        let declared = self.declared_functions();
        let contents = render_jni_native_source(self, registry, &declared, &class_name);
        KotlinFile {
            package: self.package.clone(),
            class_name,
            contents,
        }
    }

    /// Emit one Kotlin file per entry in `handles` — each becomes a
    /// `public class <ClassName>(initialPtr: Long) : NativeHandle(initialPtr)`
    /// with the standard `free()` + `private external fun <mangle_fun("freePtr")>(ptr: Long)`
    /// destructor pair, plus one instance method per `#[prebindgen]` fn
    /// listed in [`TypedHandle::functions`]. The promoted method's first
    /// opaque parameter matching the handle's Rust type is dropped — the
    /// method uses inherited `withPtr` / `consume` from [`NativeHandle`]
    /// (i.e. `this` scope) for that param, while every remaining
    /// parameter is emitted exactly as it would appear in the
    /// `JNIWrappers` top-level wrapper (including `impl Into<T>`
    /// dispatch arms and opaque-return wrapping).
    ///
    /// Functions listed under any [`TypedHandle::functions`] are skipped
    /// in [`Self::write_jni_wrappers`] — "Not mentioned functions remain
    /// in `JNIWrapper`" is the assignment rule, exposed by passing the
    /// same `handles` slice to both methods.
    ///
    /// Each handle's `kotlin_fqn` must be registered via
    /// [`Self::kotlin_type_fqn`] so the generator can map it back to its
    /// Rust type-key (which identifies the first param to drop in each
    /// promoted method's signature).
    pub(crate) fn write_typed_handles(&self, handles: &[TypedHandle<'_>]) -> Vec<KotlinFile> {
        let mut written = Vec::new();
        for handle in handles {
            let (package, class_name) = match handle.kotlin_fqn.rsplit_once('.') {
                Some((p, c)) => (p.to_string(), c.to_string()),
                None => (String::new(), handle.kotlin_fqn.to_string()),
            };
            written.push(KotlinFile {
                contents: render_typed_handle_source(self, &package, &class_name, handle.rust_doc),
                package,
                class_name,
            });
        }
        written
    }
}

/// The banner every generated Kotlin file opens with. Matched verbatim when
/// splitting a fragment's header so it isn't duplicated into the merged body,
/// and re-emitted once at the top of each merged file.
const KOTLIN_BANNER: &str = "// Auto-generated by JniGen — do not edit by hand.";

/// Split one generated Kotlin fragment into its `import` set and its body.
///
/// Only the **header** is parsed: the leading banner line, an optional
/// `package` line, and a run of blank / `import` lines (all at column 0, as
/// the generator emits them). The first line that is none of those starts the
/// body, which is taken verbatim from there on — so a `//`/`/** */` comment or
/// any later line that happens to begin with `import `/`package ` inside the
/// body is preserved untouched.
fn split_kotlin_contents(contents: &str) -> (Vec<String>, String) {
    let lines: Vec<&str> = contents.lines().collect();
    let mut imports = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        if line == KOTLIN_BANNER || line.starts_with("package ") || line.trim().is_empty() {
            i += 1;
            continue;
        }
        if let Some(rest) = line.strip_prefix("import ") {
            imports.push(rest.trim().to_string());
            i += 1;
            continue;
        }
        break;
    }
    (imports, lines[i..].join("\n").trim().to_string())
}

/// Merge per-declaration [`KotlinFile`] fragments into ONE file per package.
///
/// All fragments sharing a `package` are concatenated into a single file named
/// after the package's last segment (`io.zenoh.jni.config` → `config.kt`). The
/// union of their imports is emitted once, dropping any import that targets the
/// merged file's own package (the symbol is now declared in the same file, so
/// an explicit import would be a redeclaration). Packages are emitted in sorted
/// order; within a package fragments keep their (deterministic) emission order.
///
/// Fails with [`WriteKotlinError::Other`] on a duplicate declaration identity
/// within a package, or on an `import` simple-name collision (two distinct FQNs
/// sharing a simple name in the same merged file) — both of which would produce
/// uncompilable Kotlin.
fn merge_package_files(fragments: Vec<KotlinFile>) -> Result<Vec<KotlinFile>, WriteKotlinError> {
    let mut groups: BTreeMap<String, Vec<KotlinFile>> = BTreeMap::new();
    for f in fragments {
        groups.entry(f.package.clone()).or_default().push(f);
    }

    let mut out = Vec::new();
    for (package, group) in groups {
        // Two fragments must not claim the same Kotlin file identity within a
        // package — a single merged file can't hold two declarations of it.
        let mut seen: BTreeSet<&str> = BTreeSet::new();
        for f in &group {
            if !seen.insert(f.class_name.as_str()) {
                return Err(WriteKotlinError::Other(format!(
                    "duplicate declaration `{}` in package `{}`",
                    f.class_name, package
                )));
            }
        }

        let mut imports: BTreeSet<String> = BTreeSet::new();
        let mut bodies: Vec<String> = Vec::new();
        for f in &group {
            let (imps, body) = split_kotlin_contents(&f.contents);
            for imp in imps {
                let imp_pkg = imp.rsplit_once('.').map(|(p, _)| p).unwrap_or("");
                // Same-package symbols are now in this very file — no import.
                if imp_pkg == package {
                    continue;
                }
                imports.insert(imp);
            }
            if !body.is_empty() {
                bodies.push(body);
            }
        }

        // A merged file can import each simple name from only one FQN.
        let mut by_simple: BTreeMap<&str, &str> = BTreeMap::new();
        for imp in &imports {
            let simple = imp.rsplit_once('.').map(|(_, s)| s).unwrap_or(imp.as_str());
            if let Some(prev) = by_simple.insert(simple, imp.as_str()) {
                return Err(WriteKotlinError::Other(format!(
                    "import simple-name collision in package `{}`: `{}` and `{}`",
                    package, prev, imp
                )));
            }
        }

        let class_name = package
            .rsplit('.')
            .next()
            .filter(|s| !s.is_empty())
            .unwrap_or("Generated")
            .to_string();

        let mut s = String::new();
        s.push_str(KOTLIN_BANNER);
        s.push('\n');
        if !package.is_empty() {
            s.push_str(&format!("package {}\n\n", package));
        }
        if !imports.is_empty() {
            for imp in &imports {
                s.push_str(&format!("import {}\n", imp));
            }
            s.push('\n');
        }
        s.push_str(&bodies.join("\n\n"));
        if !s.ends_with('\n') {
            s.push('\n');
        }

        out.push(KotlinFile {
            package,
            class_name,
            contents: s,
        });
    }
    Ok(out)
}
