//! Kotlin source-file renderers (enum / data-class / typed-handle /
//! package / native / wrapper-fn) for the JNI back-end.
//!
//! Carved from the former `jni_kotlin_ext.rs`; shares the `jni` namespace
//! via `use super::*`.

use super::*;

// ── Safe-wrapper emitters ──────────────────────────────────────────────

/// One generated Kotlin `enum class` source — variants in
/// SCREAMING_SNAKE_CASE, each carrying the Rust discriminant as a
/// `val value: Int`, plus a `fromInt(value: Int)` companion. Mirrors
/// the hand-written `io.zenoh.qos.Priority` shape so adapter code that
/// already speaks the `.value` / `.fromInt(...)` idiom keeps working.
pub(crate) fn render_enum_source(
    package: &str,
    class_name: &str,
    item_enum: &syn::ItemEnum,
) -> String {
    // Same discriminant source of truth the Rust `jint → variant` decode
    // uses, so Kotlin `value(N)` and the generated decode agree.
    let variants: Vec<(String, i64)> =
        crate::api::lang::jnigen::util::enum_discriminant_values(item_enum)
            .into_iter()
            .map(|(ident, value)| {
                (
                    crate::api::lang::jnigen::util::camel_to_screaming_snake(&ident.to_string()),
                    value,
                )
            })
            .collect();

    let mut s = String::new();
    s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !package.is_empty() {
        s.push_str(&format!("package {}\n\n", package));
    }
    s.push_str(&format!(
        "/** JVM-side surface for the native Rust `{}` enum. */\n",
        item_enum.ident
    ));
    s.push_str(&format!(
        "public enum class {}(public val value: Int) {{\n",
        class_name
    ));
    for (i, (name, value)) in variants.iter().enumerate() {
        let sep = if i + 1 == variants.len() { ";" } else { "," };
        s.push_str(&format!("    {}({}){}\n", name, value, sep));
    }
    s.push('\n');
    s.push_str("    public companion object {\n");
    // `@JvmStatic` exposes `fromInt` as a real static method on the enum
    // class itself (rather than only on the `Companion` nested class). The
    // generated struct-encoder calls it via `env.call_static_method`, which
    // wouldn't find a companion-only method.
    s.push_str(&format!(
        "        @JvmStatic\n        public fun fromInt(value: Int): {} = entries.first {{ it.value == value }}\n",
        class_name
    ));
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

/// One generated Kotlin `data class` source for a `data_class`-declared Rust
/// struct.
pub(crate) fn render_data_class_source(
    ext: &JniGen,
    package: &str,
    class_name: &str,
    item_struct: &syn::ItemStruct,
    registry: &Registry<KotlinMeta>,
) -> String {
    let fields_named = match &item_struct.fields {
        syn::Fields::Named(n) => &n.named,
        _ => {
            panic!(
                "render_data_class_source: struct `{}` must use named fields to map onto Kotlin data class properties",
                item_struct.ident
            )
        }
    };

    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut field_lines: Vec<String> = Vec::new();
    // Track per-field destructible (name, folded close strategy) so the
    // bottom emitter can produce a matching `close()` body for each.
    let mut destructible_fields: Vec<(
        String,
        crate::api::lang::jnigen::jni::FoldStrategy,
    )> = Vec::new();
    for field in fields_named {
        let field_ident = field.ident.as_ref().unwrap_or_else(|| {
            panic!(
                "render_data_class_source: struct `{}` has an unnamed field in named-fields context",
                item_struct.ident
            )
        });
        let kotlin_field_name = kt_snake_to_camel(&field_ident.to_string());
        let override_prefix = "";

        // Projection field (opaque handle or value class): the typed Kotlin
        // type (`ZKeyExpr?`, `List<ZKeyExpr>`, `ZenohId`, `List<ZenohId>`, …)
        // is derived from the folded `Projection` the type-unfolding mechanism
        // propagated onto this field's converter metadata, instead of a
        // syntactic `Option<T>` peel. Closeable `close()` emission applies
        // only to `Handle` kind (and only when owned); value classes are
        // erased to their inner wire, so they never close.
        let field_projection = registry
            .output_entry(&field.ty)
            .and_then(|e| e.metadata.projection.clone())
            .or_else(|| {
                registry
                    .input_entry(&field.ty)
                    .and_then(|e| e.metadata.projection.clone())
            });
        if let Some(h) = field_projection {
            let fqn = ext
                .kotlin_fqn(&h.leaf_key)
                .map(|v| v.to_string())
                .unwrap_or_else(|| {
                    panic!(
                        "render_data_class_source: projection field `{}.{}` leaf `{}` has no \
                         Kotlin FQN registered (ptr_class / value_class)",
                        item_struct.ident, field_ident, h.leaf_key
                    )
                });
            let short = register_fqn(&fqn, &mut imports);
            field_lines.push(format!(
                "    {override_prefix}val {kotlin_field_name}: {},",
                render_handle_type(&h.strategy, &short)
            ));
            if matches!(
                h.kind,
                crate::api::lang::jnigen::jni::ProjectionKind::Handle
            ) && h.owned
            {
                destructible_fields.push((kotlin_field_name, h.strategy));
            }
            continue;
        }

        let kotlin_ty = registry
            .output_entry(&field.ty)
            .and_then(|e| e.metadata.kotlin_name.clone())
            .or_else(|| registry.input_entry(&field.ty).and_then(|e| e.metadata.kotlin_name.clone()))
            .unwrap_or_else(|| {
                panic!(
                    "render_data_class_source: field `{}.{}` has no Kotlin type mapping; register converters before declaring data_class",
                    item_struct.ident,
                    field_ident
                )
            });
        let short = register_fqn(&kotlin_ty, &mut imports);
        // `Option<T>` whose wire is a JNI primitive (jlong/jint/jboolean/…)
        // and that *isn't* an opaque handle (handled above) is encoded by
        // the struct emitter as the bare primitive with a sentinel for
        // `None` (0 / 0.0 / false). The Kotlin field must match that JVM
        // slot: declare it non-nullable so the constructor signature
        // stays primitive (`J` vs `Ljava/lang/Long;`). Nullable boxing
        // for non-handle primitives would require generator-side changes
        // in `struct_output_body` to `Long.valueOf(...)`.
        let wire = registry
            .output_entry(&field.ty)
            .map(|e| e.destination.clone());
        let primitive_wire = wire
            .as_ref()
            .map(|w| crate::api::lang::jnigen::jni::is_jni_primitive(w))
            .unwrap_or(false);
        let optional_suffix = if is_option_type(&field.ty) && !primitive_wire {
            "?"
        } else {
            ""
        };
        field_lines.push(format!(
            "    {override_prefix}val {kotlin_field_name}: {short}{optional_suffix},"
        ));
    }

    // `fromParts` companion factory — recursively flattened the same way as the
    // native `flatten_struct_encode`: nested data-class fields are inlined as
    // their leaf wires, so native builds the whole object graph with ONE
    // `call_static_method`. Computed here (before `import_list`) so any nested
    // child FQN it references is registered into `imports`.
    let (factory_params, factory_reconstruct) =
        flatten_struct_factory(ext, registry, item_struct, "", class_name, &mut imports, 0)
            .unwrap_or_else(|| {
                panic!(
                    "render_data_class_source: could not build fromParts factory for `{class_name}`"
                )
            });

    let mut import_list: Vec<String> = imports
        .iter()
        .filter(|fqn| {
            let pkg = fqn.rsplit_once('.').map(|(p, _)| p).unwrap_or("");
            !pkg.is_empty() && pkg != package
        })
        .cloned()
        .collect();
    import_list.sort();
    import_list.dedup();

    let mut s = String::new();
    s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !package.is_empty() {
        s.push_str(&format!("package {}\n\n", package));
    }
    for imp in &import_list {
        s.push_str(&format!("import {}\n", imp));
    }
    if !import_list.is_empty() {
        s.push('\n');
    }
    {
        s.push_str(&format!("public data class {}(\n", class_name));
        for line in &field_lines {
            s.push_str(line);
            s.push('\n');
        }
        // Supertype clause: a data class with a destructible native-handle
        // field implements `AutoCloseable`; otherwise no supertype.
        let supertypes: Vec<String> = if !destructible_fields.is_empty() {
            vec!["AutoCloseable".to_string()]
        } else {
            vec![]
        };
        if supertypes.is_empty() {
            s.push_str(") {\n");
        } else {
            s.push_str(&format!(") : {} {{\n", supertypes.join(", ")));
        }
        if !destructible_fields.is_empty() {
            // `close()` walks every destructible field via its folded close
            // strategy. `JNINativeHandle.close()` is idempotent
            // (Cleaner.Cleanable.clean() invokes exactly once), so calling
            // this multiple times — or alongside the cleaner's own firing on
            // GC — is safe. NOTE: `data class` copy() shares the handle
            // reference between copies; if you intend to close independently,
            // don't copy this class.
            s.push_str("    override fun close() {\n");
            for (fname, strategy) in &destructible_fields {
                s.push_str(&format!(
                    "        {}\n",
                    render_handle_close(strategy, fname)
                ));
            }
            s.push_str("    }\n\n");
        }
        s.push_str("    public companion object {\n");
        // `fromParts` factory: native (`struct_output_body`) makes ONE
        // `call_static_method` passing the whole graph's flattened leaf wires;
        // this factory reassembles it (incl. nested `Child.fromParts(...)`) in
        // JVM bytecode. `public`, not `internal`: an `internal` fun is mangled
        // to `fromParts$<module>`, unresolvable by native (`NoSuchMethodError`).
        s.push_str("        @JvmStatic\n");
        s.push_str("        public fun fromParts(\n");
        for (i, (name, ty)) in factory_params.iter().enumerate() {
            let comma = if i + 1 < factory_params.len() { "," } else { "" };
            s.push_str(&format!("            {name}: {ty}{comma}\n"));
        }
        s.push_str(&format!(
            "        ): {class_name} =\n            {factory_reconstruct}\n"
        ));
        s.push_str("    }\n");
        s.push_str("}\n");
    }
    s
}

pub(crate) fn render_data_class_aliases_source(package: &str, aliases: &[(String, String)]) -> String {
    let mut pairs = aliases.to_vec();
    pairs.sort_by(|a, b| a.0.cmp(&b.0));
    pairs.dedup_by(|a, b| a.0 == b.0 && a.1 == b.1);

    let mut s = String::new();
    s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !package.is_empty() {
        s.push_str(&format!("package {}\n\n", package));
    }
    s.push_str("// Compatibility aliases for legacy un-mangled data-class references.\n");
    for (legacy, current) in pairs {
        s.push_str(&format!("public typealias {} = {}\n", legacy, current));
    }
    s
}

/// Render one typed-handle Kotlin source file. Pure-shell form (with
/// the closure `|n| format!("{n}ViaJNI")` installed via
/// [`JniGen::kotlin_fun_name_mangle`]):
///
/// ```kotlin
/// public class JNIFoo(initialPtr: Long) : NativeHandle(initialPtr) {
///     public fun free() = free { freePtrViaJNI(it) }
///     private external fun freePtrViaJNI(ptr: Long)
/// }
/// ```
///
/// When `promoted_functions` is non-empty, one extra instance method is
/// appended per `#[prebindgen]` fn — the matching opaque first param
/// (Rust type-key = `promoted_rust_key`) is dropped from the Kotlin
/// signature, and its `withPtr` / `consume` wrapper uses the
/// inherited [`NativeHandle`] scope.
///
/// The free-pointer extern name is built as
/// `<mangle_fun("freePtr")>`. Kotlin/JVM's JNI name mangler binds it
/// to the matching `Java_<pkg>_<class>_<mangle_fun("freePtr")>`
/// extern on the Rust side (the auto-generated destructor).
pub(crate) fn render_typed_handle_source(
    ext: &JniGen,
    package: &str,
    class_name: &str,
    rust_doc_name: &str,
) -> String {
    // The typed handle is a pure shell — `ptr` slot + `close()`/`take()` +
    // the `freePtr` extern. All functions are emitted as flat free functions
    // in their namespace package; nothing is promoted onto the class.
    let mut imports: BTreeSet<String> = BTreeSet::new();
    // Every typed handle extends the shared `NativeHandle` base (emitted in
    // `ext.package`); pull it in unless we *are* that package.
    if !ext.package.is_empty() {
        imports.insert(format!("{}.NativeHandle", ext.package));
    }

    // Imports filtered the same way as render_kotlin_interface — drop
    // entries whose package matches our own (no need to import locals).
    let mut import_list: Vec<String> = imports
        .iter()
        .filter(|fqn| {
            let pkg = fqn.rsplit_once('.').map(|(p, _)| p).unwrap_or("");
            !pkg.is_empty() && pkg != package
        })
        .cloned()
        .collect();
    import_list.sort();
    import_list.dedup();

    let mut s = String::new();
    s.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !package.is_empty() {
        s.push_str(&format!("package {}\n\n", package));
    }
    if !import_list.is_empty() {
        for imp in &import_list {
            s.push_str(&format!("import {}\n", imp));
        }
        s.push('\n');
    }
    let free_extern = ext.mangle_fun("freePtr");
    s.push_str(&format!(
        "/** Typed handle for a native Zenoh `{}`. */\n",
        rust_doc_name
    ));
    // Every typed handle extends the shared `NativeHandle` base, which owns
    // the `@Volatile` pointer slot (`ptr`) and its monitor — that common
    // supertype is what lets `render_wrapper_fn` collect a `List<NativeHandle>`
    // and lock it in one pointer-sorted, deadlock-safe pass. The subclass keeps
    // its own type-specific `close()`/`take()`/`freePtr`.
    s.push_str(&format!(
        "public class {class_name}(initialPtr: Long) : NativeHandle(initialPtr) {{\n",
    ));
    s.push_str("    @Synchronized\n");
    s.push_str("    override fun close() {\n");
    s.push_str("        val p = ptr\n");
    s.push_str("        if (p != 0L) {\n");
    s.push_str("            ptr = 0L\n");
    s.push_str(&format!("            {free_extern}(p)\n"));
    s.push_str("        }\n");
    s.push_str("    }\n\n");
    // Transfer ownership of the native pointer into a fresh handle, leaving
    // this one empty. Lets a callback receiver retain a handle that the
    // framework would otherwise `close()` when the callback returns.
    s.push_str("    @Synchronized\n");
    s.push_str(&format!("    public fun take(): {class_name} {{\n"));
    s.push_str("        val p = ptr\n");
    s.push_str("        ptr = 0L\n");
    s.push_str(&format!("        return {class_name}(p)\n"));
    s.push_str("    }\n");
    // Companion object carries the `@JvmStatic external fun freePtr(ptr: Long)`
    // called by `close()` above.
    s.push('\n');
    s.push_str("    public companion object {\n");
    s.push_str(&format!(
        "        @JvmStatic\n        external fun {free_extern}(ptr: Long)\n",
    ));
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

/// Emit the package-level wrapper file: one safe top-level wrapper per
/// `#[prebindgen]` fn whose name is in `promoted` (i.e. listed in
/// `package_methods.methods`). Each wrapper delegates to the centralized
/// Native object's matching `external fun`. Opaque-handle parameters
/// (detected via the input converter returning `OwnedObject<T>`) become
/// `NativeHandle`; the wrapper body nests `withPtr` / `consume` per the
/// syntactic shape. Non-opaque parameters pass through with the Kotlin
/// type from `kotlin_types`.
pub(crate) fn render_jni_package_source(
    ext: &JniGen,
    registry: &Registry<KotlinMeta>,
    functions: &[MethodEntry],
    package: &str,
) -> String {
    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut body = String::new();

    for entry in functions {
        let (item_fn, _loc) = registry
            .functions
            .get(&entry.rust_ident)
            .unwrap_or_else(|| {
                panic!(
                    "render_jni_package_source: function `{}` registered via .function(...) is \
                 not in the prebindgen registry — check the spelling against the matching \
                 `#[prebindgen]` Rust fn name.",
                    entry.rust_ident,
                )
            });
        if let Some(block) = render_wrapper_fn(
            ext,
            item_fn,
            registry,
            &mut imports,
            entry.kotlin_name_override.as_deref(),
        ) {
            body.push_str(&block);
            body.push('\n');
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !package.is_empty() {
        out.push_str(&format!("package {}\n\n", package));
    }
    // Exception imports (if any) are added to `imports` by the per-wrapper
    // `@Throws` emission, so no error class is hardcoded here.
    for imp in &imports {
        out.push_str(&format!("import {}\n", imp));
    }
    if !ext.package.is_empty() {
        out.push_str(&format!(
            "import {}.{}\n",
            ext.package,
            ext.jni_native_class_name()
        ));
    }
    out.push('\n');
    out.push_str(&body);
    out
}

/// Render the centralized `internal object <jni_native_class>` holder:
/// one `external fun` per `#[prebindgen]` function, at the JNI **wire**
/// level. Parameter and return types match what the Rust extern
/// receives:
///   * opaque-handle (Borrow/Consume) → jlong → `Long`
///   * `enum_class`                  → jint  → `Int` (call passes `.value`)
///   * `Any` (impl-Into Dispatch)     → JObject → `Any`
///   * everything else                → entry's high-level Kotlin name
/// Opaque returns become `Long`; every other return uses
/// [`classify_return`]'s `kt_return` (Unit is empty string). No `init`
/// block is emitted — the holder stays free of any wrapper-layer
/// reference; the wrapper-layer call sites are responsible for
/// triggering `System.load` before invoking any extern.
pub(crate) fn render_jni_native_source(
    ext: &JniGen,
    registry: &Registry<KotlinMeta>,
    declared: &HashSet<syn::Ident>,
    class_name: &str,
) -> String {
    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut body = String::new();

    let mut idents: Vec<&syn::Ident> = registry.functions.keys().collect();
    idents.sort();
    for ident in idents {
        if !declared.contains(ident) {
            continue;
        }
        let (item_fn, _loc) = &registry.functions[ident];
        if let Some(line) = render_extern_decl(ext, item_fn, registry, &mut imports) {
            body.push_str(&line);
            body.push('\n');
        }
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by JniGen — do not edit by hand.\n");
    if !ext.package.is_empty() {
        out.push_str(&format!("package {}\n\n", ext.package));
    }
    for imp in &imports {
        out.push_str(&format!("import {}\n", imp));
    }
    out.push('\n');
    out.push_str(&format!("internal object {} {{\n", class_name));
    for line in body.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str("}\n");
    out
}

/// Render one `external fun <mangle_fun(name)>(…): <wire-return>` line
/// at the JNI **wire** level (matches what the Rust extern receives):
///   * opaque-handle (Borrow/Consume) → jlong → `Long`
///   * `enum_class`                  → jint  → `Int` (call passes `.value`)
///   * `Any` (impl-Into Dispatch)     → JObject → `Any`
///   * everything else                → entry's high-level Kotlin name
/// Opaque returns become `Long`; every other return uses
/// [`classify_return`]'s `kt_return` (Unit is empty string).
/// Returns `None` if any parameter's input converter isn't resolved.
/// Expand a function's inputs into the effective parameter list seen by the
/// Kotlin wrapper + extern declaration: a parameter carrying a
/// constructor-expansion [`FoldPlan`] is replaced by its flattened leaves
/// (each a normal `(name, type)`); every other parameter passes through. The
/// Rust extern (`emit_jni_function_wrapper`) folds the leaves back into the
/// built value separately.
pub(crate) fn effective_inputs(
    registry: &Registry<KotlinMeta>,
    f: &syn::ItemFn,
) -> Vec<(syn::Ident, syn::Type)> {
    let mut out = Vec::new();
    for input in &f.sig.inputs {
        let syn::FnArg::Typed(pt) = input else {
            continue;
        };
        let syn::Pat::Ident(pid) = &*pt.pat else {
            continue;
        };
        if let Some(plan) = registry
            .expansion_plans
            .get(&(f.sig.ident.clone(), pid.ident.clone()))
        {
            for leaf in &plan.leaves {
                out.push((leaf.name.clone(), leaf.ty.clone()));
            }
        } else {
            out.push((pid.ident.clone(), (*pt.ty).clone()));
        }
    }
    out
}

pub(crate) fn render_extern_decl(
    ext: &JniGen,
    f: &syn::ItemFn,
    registry: &Registry<KotlinMeta>,
    imports: &mut BTreeSet<String>,
) -> Option<String> {
    use std::fmt::Write;

    let rust_name = f.sig.ident.to_string();
    let kt_name = kt_snake_to_camel(&rust_name);
    let jni_call = ext.mangle_fun(&kt_name);

    let mut params: Vec<(String, String)> = Vec::new();
    for (eff_ident, eff_ty) in effective_inputs(registry, f) {
        let name = kt_param_name(&eff_ident.to_string());
        let arg_ty = &eff_ty;

        // Flattenable data_class param → expand into its leaf wire params
        // (same plan the native wrapper + call site use).
        if let Some(plan) = crate::api::lang::jnigen::jni::build_flat_input_plan(
            ext, registry, &eff_ident, arg_ty, "",
        ) {
            for leaf in &plan.leaves {
                let short = register_fqn(&leaf.kt_wire_ty, imports);
                params.push((leaf.kt_name.clone(), short));
            }
            continue;
        }

        let entry = registry.input_entry(arg_ty)?;

        // An opaque-**handle** projection (direct `&T`/`T`, `Option<&T>`, or
        // by-value `Option<T>`) crosses the JNI wire as a primitive `jlong`
        // with `0` encoding `None` — so the extern param is a non-null `Long`,
        // and the `?` lives only on the typed-wrapper surface. (`value_blob`
        // projections are NOT handles; they keep their `ByteArray` wire and
        // can be nullable.)
        let proj_is_handle = entry
            .metadata
            .projection
            .as_ref()
            .map(|p| p.kind == crate::api::lang::jnigen::jni::ProjectionKind::Handle)
            .unwrap_or(false);
        let optional = is_option_type(arg_ty) && !proj_is_handle;

        let kt_type_raw = if proj_is_handle {
            "Long".to_string()
        } else if ext.is_kotlin_enum(&enum_probe_type(arg_ty)) {
            // Enum (incl. `Option<enum>`) crosses as jint → Kotlin `Int`; the
            // wrapper passes `.value` / `?.value`. The Rust converter unboxes a
            // `java.lang.Integer`, so the extern must declare `Int`/`Int?`, never
            // the enum object.
            "Int".to_string()
        } else {
            entry.metadata.kotlin_name.clone()?
        };
        let short = register_fqn(&kt_type_raw, imports);
        let suffix = if optional { "?" } else { "" };
        params.push((name, format!("{short}{suffix}")));
    }
    // Output (data) expansion: a **callback** delivery (`deconstruct_output`)
    // appends the lambda(s) before the error sink and returns the erased result
    // (`Any?`). A **return** delivery (`convert_output`) appends nothing and
    // returns the real converted wire (handled in `wire_return` below, keyed on
    // `convert_out_ty`).
    use crate::api::core::unfold::Delivery;
    let unfold = registry.unfold_plans.get(&f.sig.ident);
    let callback_unfold = unfold.filter(|p| p.delivery == Delivery::Callback);
    if let Some(plan) = callback_unfold {
        if matches!(plan.shape, crate::api::core::unfold::UnfoldShape::Iterable(_)) {
            // `acc` is the unbounded accumulator `A` (may be nullable) → `Any?`;
            // `fold` is the non-null adapter callback.
            params.push(("acc".to_string(), "Any?".to_string()));
            params.push(("fold".to_string(), "Any".to_string()));
        } else {
            params.push(("build".to_string(), "Any".to_string()));
        }
    }
    // Trailing error-sink callback — every extern accepts one (see
    // `signal_error` / the wrapper's default sink). `Any` at the wire level
    // (JObject); the wrapper passes an `ErrorSink` instance.
    params.push(("errorSink".to_string(), "Any".to_string()));

    let wire_return = if callback_unfold.is_some() {
        "Any?".to_string()
    } else {
        // For a `convert_output` (Return) the wire is the converted single
        // value's; otherwise the function's own return.
        let ret_decl: syn::ReturnType = match unfold.and_then(|p| p.convert_out_ty.clone()) {
            Some(cv) => syn::parse_quote!(-> #cv),
            None => f.sig.output.clone(),
        };
        let (kt_return, projection) = classify_return(ext, &ret_decl, registry, imports)?;
        // enum_class returns cross the JNI wire as jint → Kotlin `Int`.
        // The public wrapper converts back using `EnumType.fromInt(Int)`.
        let is_enum_return = return_is_kotlin_enum(ext, &ret_decl, registry);
        // JNI extern's wire return: handle projections wire as `Long` (the boxed
        // jlong gets wrapped); value-class projections wire as their inner
        // converter's Kotlin type folded through the projection's strategy (the
        // value class is erased to that inner). Enums wire as `Int`; everything
        // else is the declared return.
        match &projection {
            Some(p) => projection_wire_return(p),
            None if is_enum_return => "Int".to_string(),
            None => kt_return,
        }
    };

    let formals = params
        .iter()
        .map(|(n, t)| format!("{n}: {t}"))
        .collect::<Vec<_>>()
        .join(", ");

    let mut line = String::new();
    if wire_return.is_empty() {
        write!(&mut line, "external fun {jni_call}({formals})").ok()?;
    } else {
        write!(
            &mut line,
            "external fun {jni_call}({formals}): {wire_return}"
        )
        .ok()?;
    }
    Some(line)
}

/// Emit a single top-level (free-function) wrapper. Returns `None` if the
/// function has a parameter whose Kotlin type isn't registered (in that case we
/// skip the function rather than panicking — the legacy `JNINative.kt`
/// retains the unwrapped external fun so callers still have an
/// escape hatch).
///
/// Every `#[prebindgen]` function is emitted as a flat namespaced free function
/// — opaque-handle parameters are ordinary `NativeHandle` params, locked via the
/// per-call `withSortedHandleLocks` scaffold. There is no receiver promotion /
/// instance-method representation: the base library is flat.
pub(crate) fn render_wrapper_fn(
    ext: &JniGen,
    f: &syn::ItemFn,
    registry: &Registry<KotlinMeta>,
    imports: &mut BTreeSet<String>,
    kotlin_name_override: Option<&str>,
) -> Option<String> {
    use std::fmt::Write;

    let rust_name = f.sig.ident.to_string();
    // The Kotlin extern in `JNINative` is keyed on the Rust ident
    // (`kt_snake_to_camel(rust_name)` → `ext.mangle_fun`). The per-entry
    // `.name("...")` override only changes the *user-facing* Kotlin
    // wrapper name; the JNI call still has to hit the one extern that
    // the Rust extern actually emits.
    let default_kt_name = kt_snake_to_camel(&rust_name);
    let kt_name = match kotlin_name_override {
        Some(n) => n.to_string(),
        None => default_kt_name.clone(),
    };
    let jni_call = ext.mangle_fun(&default_kt_name);

    // Classify each parameter.
    struct Param {
        kt_name: String,
        kt_type: String,
        mode: ParamMode,
        /// `true` when the param's Rust type is a `enum_class`-declared
        /// enum: the high-level Kotlin signature uses the typed enum
        /// (`Priority`), but the underlying JNI `external fun` declares
        /// the param as `Int` (jint wire). The wrapper bridges the two
        /// by passing `<name>.value` at the call site.
        as_enum_value: bool,
    }
    enum ParamMode {
        Borrow,  // &T opaque-handle → withPtr
        Consume, // T  opaque-handle → consume
        /// `Option<&T>` / `Option<&mut T>` opaque-handle → `withPtrOrZero`.
        /// Nullable typed-handle param; the wrapper runs the body under
        /// the read lock when the handle is non-null and with `0L` when
        /// null. The Rust converter materializes `Option<OwnedObject<T>>`
        /// and the call site uses `.as_deref()` / `.as_deref_mut()`.
        BorrowNullable,
        /// By-value `Option<T>` opaque-handle → nullable consume. Same as
        /// [`Self::Consume`] but the typed param is nullable (`T?`): `0L` when
        /// absent, and the handle's `ptr` slot is nulled after the call only
        /// when present. The Rust converter consumes the `Box` to `Option<T>`.
        ConsumeNullable,
        PassThrough,
        /// Value-projection param (`value_blob`): a Kotlin
        /// `@JvmInline value class` that is **not** a lockable handle. The
        /// Kotlin param type is the value-class FQN; the call site passes the
        /// unwrapped inline-class field (`<name>.<field>`) so the `JNINative`
        /// extern receives the erased inner wire (e.g. `ByteArray`). No lock.
        ValueUnwrap {
            field: String,
        },
        /// Flattenable `data_class` param: the high-level Kotlin signature
        /// keeps the typed object, but the `JNINative` call destructures it
        /// into the leaf access expressions (no `JObject` crosses, so the
        /// Rust side skips `env.get_field(...)`). The strings are the
        /// per-leaf call-site expressions in plan order.
        FlattenStruct { accesses: Vec<String> },
        /// `impl Fn(args)` callback param: typed Kotlin lambda over the
        /// flattened leaves of each arg's callback plan (whole arg when
        /// plan-less), erased to `Any` at the extern tier — the same shape as
        /// the unfold `build`/`onError` lambdas. `call_arg` is the call-site
        /// expression: the param itself, or a value-blob rebuilding adapter.
        Callback { call_arg: String },
    }

    let mut params: Vec<Param> = Vec::new();
    for (eff_ident, eff_ty) in effective_inputs(registry, f) {
        let name = kt_param_name(&eff_ident.to_string());
        let arg_ty = &eff_ty;

        // `impl Fn(args)` param: a typed Kotlin lambda whose parameters are
        // the flattened leaves of each arg's callback plan (the arg whole when
        // its type has no canonical output) — mirroring the unfold builder
        // lambda. The extern receives it erased (`Any`); value-blob leaves get
        // a rebuilding adapter at the call site, like the unfold path.
        if let Some(cb_args) = extract_fn_trait_args(arg_ty) {
            // (name, out_ty, nullable) per delivered lambda leaf — names from
            // the plan's accessor paths (or the bare arg type when plan-less).
            let mut leaf_tys: Vec<(String, syn::Type, bool)> = Vec::new();
            for (i, t) in cb_args.iter().enumerate() {
                if let Some(plan) = registry.callback_arg_plans.get(&TypeKey::from_type(t)) {
                    leaf_tys.extend(
                        plan_leaf_names(registry, plan)
                            .into_iter()
                            .zip(plan.leaves.iter())
                            .map(|(n, l)| (n, l.out_ty.clone(), l.nullable)),
                    );
                } else {
                    leaf_tys.push((whole_value_name(t, i), t.clone(), is_option_type(t)));
                }
            }
            let mut leaf_names: Vec<String> =
                leaf_tys.iter().map(|(n, _, _)| n.clone()).collect();
            dedup_kt_param_names(&mut leaf_names);
            let mut builder_kts: Vec<String> = Vec::with_capacity(leaf_tys.len());
            let mut adapter_params: Vec<String> = Vec::with_capacity(leaf_tys.len());
            let mut wraps: Vec<String> = Vec::with_capacity(leaf_tys.len());
            let mut needs_adapter = false;
            for (k, (_, out_ty, nullable)) in leaf_tys.iter().enumerate() {
                let pk = &leaf_names[k];
                let (builder_kt, wire_kt, wrap, is_vb) =
                    unfold_leaf_kt(ext, registry, out_ty, *nullable, pk, imports)?;
                needs_adapter |= is_vb;
                adapter_params.push(format!("{pk}: {wire_kt}"));
                wraps.push(wrap);
                builder_kts.push(format!("{pk}: {builder_kt}"));
            }
            let kt_type = format!("({}) -> Unit", builder_kts.join(", "));
            let call_arg = if needs_adapter {
                format!(
                    "{{ {} -> {}({}) }}",
                    adapter_params.join(", "),
                    name,
                    wraps.join(", ")
                )
            } else {
                name.clone()
            };
            params.push(Param {
                kt_name: name,
                kt_type,
                mode: ParamMode::Callback { call_arg },
                as_enum_value: false,
            });
            continue;
        }

        // Strip leading reference for the type-map lookup; the registry's
        // input entry is keyed by the param as-written.
        let entry = registry.input_entry(arg_ty)?;
        // Opaque-handle params surface as their typed-handle FQN — every
        // handle is self-contained (its own ptr slot + monitor), so the
        // wrapper body inlines synchronized blocks directly on the typed
        // receiver. Detection flows from the folded `Projection` — present
        // for both `&T` and by-value `T` (the `owned` flag is orthogonal
        // to presence) — so it's the same source of truth the typed-surface
        // emitters use.
        let is_opaque = entry.metadata.projection.is_some();

        // `Option<&T>` / `Option<&mut T>` for opaque T marks the param
        // nullable; the wrapper body branches on null before lock selection.
        let is_opt_ref_opaque = is_opaque && is_option_ref(arg_ty);
        let (kt_type_raw, optional) = if is_opaque {
            let h = entry.metadata.projection.as_ref()?;
            let fqn = ext.kotlin_fqn(&h.leaf_key).map(|v| v.to_string())?;
            // Any `Option<_>` opaque param (borrowed `Option<&T>` or by-value
            // `Option<T>`) is nullable; value projections likewise. The handle
            // wire stays `jlong` with `0` = absent, so the `?` is purely the
            // typed-wrapper surface.
            (fqn, is_option_type(arg_ty))
        } else {
            // Read the Kotlin name straight off the resolved entry's
            // metadata — the rank-N handler that built this converter
            // is also the one that derived the Kotlin name (primitives
            // from `kotlin_for_wire`, wrappers inherit from inner,
            // user-declared decoders from `with_kotlin_name`).
            let kt = entry.metadata.kotlin_name.clone()?;
            let opt = is_option_type(arg_ty);
            (kt, opt)
        };

        // A projection can be a lockable opaque **handle** or a non-lockable
        // **value projection** (`value_blob` — an inline value class). Only
        // handles participate in the lock scaffold and pass a `_ptr`; value
        // projections pass their unwrapped inner field.
        let proj_kind = entry
            .metadata
            .projection
            .as_ref()
            .map(|p| p.kind.clone());
        let is_handle = matches!(
            proj_kind,
            Some(crate::api::lang::jnigen::jni::ProjectionKind::Handle)
        );
        let is_value_proj = matches!(
            proj_kind,
            Some(crate::api::lang::jnigen::jni::ProjectionKind::ValueBlob)
        );

        // Mode: handle → Borrow/Consume by Rust syntactic shape (locked).
        // Value projection → ValueUnwrap (inline-class field, no lock).
        // Everything else (primitives, callbacks, data classes) passes through.
        //
        // Flattenable data_class params are detected first: the high-level
        // signature keeps the typed object (`kt_type_raw`), but the
        // `JNINative` call destructures it into leaf args (same plan the
        // native wrapper + extern decl consume). The decision is purely
        // type-based so all three sites agree.
        let flat_plan = crate::api::lang::jnigen::jni::build_flat_input_plan(
            ext, registry, &eff_ident, arg_ty, name.as_str(),
        );
        let mode = if let Some(plan) = flat_plan {
            ParamMode::FlattenStruct {
                accesses: plan.leaves.iter().map(|l| l.kt_access.clone()).collect(),
            }
        } else if is_handle {
            let borrow = matches!(arg_ty, syn::Type::Reference(_));
            if is_opt_ref_opaque {
                ParamMode::BorrowNullable
            } else if is_option_type(arg_ty) {
                // by-value `Option<T>` opaque → nullable consume
                ParamMode::ConsumeNullable
            } else if borrow {
                ParamMode::Borrow
            } else {
                ParamMode::Consume
            }
        } else if is_value_proj {
            // `@JvmInline value class` (value_blob) param: pass the erased inner
            // field (`<name>.bytes`, or `<name>?.bytes` when Option) to the
            // extern, no lock. Supports the Direct (`T` / `&T`) and Nullable
            // (`Option<T>`) shapes; a collection layer (`Vec<value-blob>`,
            // i.e. an `Iterable` projection) still needs array codegen and is a
            // loud build-time error. The inline field is resolved off the
            // folded projection's `leaf_key`, so `Option<_>` wrappers around the
            // value blob resolve correctly.
            let proj = entry.metadata.projection.as_ref()?;
            if matches!(
                proj.strategy,
                crate::api::lang::jnigen::jni::FoldStrategy::Iterable(_)
            ) {
                panic!(
                    "render_wrapper_fn: value-blob `Vec<_>` params aren't \
                     supported yet (param `{name}`); add array codegen to lift this guard."
                );
            }
            let field = crate::api::lang::jnigen::jni::value_projection_field_for_leaf(
                ext,
                &proj.leaf_key,
            )
            .unwrap_or_else(|| {
                panic!(
                    "render_wrapper_fn: cannot determine inline-class field for value \
                     projection param `{name}`"
                )
            });
            ParamMode::ValueUnwrap { field }
        } else {
            ParamMode::PassThrough
        };

        let short = register_fqn(&kt_type_raw, imports);
        let suffix = if optional { "?" } else { "" };
        // Strip a leading `&` before the enum check — the `&Priority`
        // input converter shares Priority's converter (see the rank-1
        // `& _` arm), and the same `.value` projection applies either
        // way at the call site.
        // Detect enums through a leading `&` and through `Option<…>`, so a
        // nullable enum param passes `?.value` to the (Int?-typed) extern.
        let as_enum_value = ext.is_kotlin_enum(&enum_probe_type(arg_ty));
        params.push(Param {
            kt_name: name,
            kt_type: format!("{short}{suffix}"),
            mode,
            as_enum_value,
        });
    }

    // Output (data) expansion. The return value is delivered to a caller
    // callback per shape:
    //   * `Decompose`/`Optional` (M1–M3): decompose into leaves → `build:
    //     (L0, …) -> R` once; `<R>`, returns `R` / `R?`.
    //   * `Iterable` (M4 whole / M5 decomposed): per element, fold
    //     `(acc, leaves…) -> acc`; `<A>`, returns `A`, threads the accumulator.
    // Each leaf is delivered with its final Kotlin type; a **value_blob** leaf
    // (`@JvmInline value class`) can't be constructed Rust-side, so the wrapper
    // installs an **adapter** that applies the Kotlin-side projection wrap
    // (`ZZenohId(raw)`) before the user callback. Leaves with no value_blob ⇒
    // the callback is passed directly (M1–M4 unchanged).
    use crate::api::core::unfold::Delivery;
    let unfold = registry.unfold_plans.get(&f.sig.ident);
    let is_convert = unfold.map_or(false, |p| p.delivery == Delivery::Return);
    // `builder_param` is the trailing **lambda** param (build / fold). For the
    // `Iterable` shape, the non-lambda accumulator (`acc: A`) goes in
    // `builder_lead` — it must precede `onError` (a defaulted param) so the
    // positional-`acc` call stays valid; the trailing `fold` lambda follows.
    let mut builder_param: Option<String> = None;
    let mut builder_lead: Option<String> = None;
    let mut generic: String = String::new();
    // Extra call-site args injected before `__sink` (e.g. `build`/adapter, or
    // `acc` + the fold callback/adapter for `Iterable`).
    let mut unfold_call_args: Vec<String> = Vec::new();

    let (kt_return, projection) = if let Some(plan) = unfold.filter(|p| p.delivery == Delivery::Return) {
        // `convert_output` (Return): the wrapper returns the single converted
        // value directly — classify it exactly like a normal function whose
        // return type is `convert_out_ty`. No callback param, no generic, no
        // extra call args; the extern returns the real wire and `build_call`
        // applies the projection wrap (value_blob/handle) below.
        let cv = plan
            .convert_out_ty
            .clone()
            .expect("Return delivery carries convert_out_ty");
        let rt: syn::ReturnType = syn::parse_quote!(-> #cv);
        classify_return(ext, &rt, registry, imports)?
    } else if let Some(plan) = unfold {
        use crate::api::core::unfold::UnfoldShape;
        // The (out_ty, nullable) of each callback arg: a whole-element Iterable
        // has one (the element); otherwise the decomposed leaves.
        let arg_tys: Vec<(syn::Type, bool)> = match (&plan.shape, &plan.element) {
            (UnfoldShape::Iterable(_), Some(el)) => vec![(el.clone(), false)],
            _ => plan.leaves.iter().map(|l| (l.out_ty.clone(), l.nullable)).collect(),
        };
        // Lambda parameter names matching `arg_tys`: derived from the plan's
        // accessor paths; a whole-element Iterable delivers one `element`.
        let mut arg_names: Vec<String> = match (&plan.shape, &plan.element) {
            (UnfoldShape::Iterable(_), Some(_)) => vec!["element".to_string()],
            _ => plan_leaf_names(registry, plan),
        };
        dedup_kt_param_names(&mut arg_names);
        // Per arg: (builder_kt seen by the user, wire_kt the extern delivers,
        // wrap expr name→final). value_blob args carry a real wrap; others are
        // passthrough.
        let mut builder_kts: Vec<String> = Vec::with_capacity(arg_tys.len());
        let mut wire_kts: Vec<String> = Vec::with_capacity(arg_tys.len());
        let mut wraps: Vec<String> = Vec::with_capacity(arg_tys.len());
        let mut needs_adapter = false;
        for (k, (out_ty, nullable)) in arg_tys.iter().enumerate() {
            let pk = &arg_names[k];
            let (builder_kt, wire_kt, wrap, is_vb) =
                unfold_leaf_kt(ext, registry, out_ty, *nullable, pk, imports)?;
            needs_adapter |= is_vb;
            builder_kts.push(format!("{pk}: {builder_kt}"));
            wire_kts.push(wire_kt);
            wraps.push(wrap);
        }
        let is_iterable = matches!(plan.shape, UnfoldShape::Iterable(_));
        // Adapter param list `name0: W0, name1: W1, …` and the wrapped-call
        // arg list.
        let adapter_params = wire_kts
            .iter()
            .enumerate()
            .map(|(k, w)| format!("{}: {w}", arg_names[k]))
            .collect::<Vec<_>>()
            .join(", ");
        let wrapped_args = wraps.join(", ");
        if is_iterable {
            generic = "<A> ".to_string();
            builder_lead = Some("acc: A".to_string());
            builder_param = Some(format!("fold: (acc: A, {}) -> A", builder_kts.join(", ")));
            unfold_call_args.push("acc".to_string());
            if needs_adapter {
                let sep = if adapter_params.is_empty() { "" } else { ", " };
                unfold_call_args.push(format!(
                    "{{ __a: A{sep}{adapter_params} -> fold(__a, {wrapped_args}) }}"
                ));
            } else {
                unfold_call_args.push("fold".to_string());
            }
            ("A".to_string(), None)
        } else {
            generic = "<R> ".to_string();
            builder_param = Some(format!("build: ({}) -> R", builder_kts.join(", ")));
            if needs_adapter {
                unfold_call_args.push(format!(
                    "{{ {adapter_params} -> build({wrapped_args}) }}"
                ));
            } else {
                unfold_call_args.push("build".to_string());
            }
            let kt = match &plan.shape {
                UnfoldShape::Optional(_) => "R?".to_string(),
                _ => "R".to_string(),
            };
            (kt, None)
        }
    } else {
        classify_return(ext, &f.sig.output, registry, imports)?
    };
    // enum_class returns cross the JNI wire as jint → Kotlin `Int`.
    // Detect this so `build_call` can wrap the result with `fromInt`.
    let is_enum_return = !unfold.is_some() && return_is_kotlin_enum(ext, &f.sig.output, registry);

    // Build the JNINative call. Every param maps to exactly one call arg
    // (or several, for a flattened data_class).
    let build_call = || -> String {
        let mut args: Vec<String> = Vec::with_capacity(params.len());
        for p in params.iter() {
            // Flattened data_class param expands into multiple call args
            // (the leaf destructure expressions, in plan order).
            if let ParamMode::FlattenStruct { accesses } = &p.mode {
                args.extend(accesses.iter().cloned());
                continue;
            }
            let arg = match &p.mode {
                ParamMode::Borrow
                | ParamMode::Consume
                | ParamMode::BorrowNullable
                | ParamMode::ConsumeNullable => format!("{}_ptr", p.kt_name),
                ParamMode::ValueUnwrap { field } => {
                    // Inline value class → pass its erased inner field to the
                    // extern (e.g. `z.bytes`: a `ByteArray`). A nullable value
                    // class (`ZBytes?`) safe-navigates so it stays `ByteArray?`.
                    if p.kt_type.ends_with('?') {
                        format!("{}?.{}", p.kt_name, field)
                    } else {
                        format!("{}.{}", p.kt_name, field)
                    }
                }
                ParamMode::PassThrough => {
                    if p.as_enum_value {
                        // Enum → its `Int` discriminant for the extern. Nullable
                        // enum (`Enum?`) uses `?.value` so it stays `Int?`.
                        if p.kt_type.ends_with('?') {
                            format!("{}?.value", p.kt_name)
                        } else {
                            format!("{}.value", p.kt_name)
                        }
                    } else {
                        p.kt_name.clone()
                    }
                }
                // Callback lambda → the param itself (the extern takes the
                // erased `Any`), or its value-blob rebuilding adapter.
                ParamMode::Callback { call_arg } => call_arg.clone(),
                ParamMode::FlattenStruct { .. } => {
                    unreachable!("FlattenStruct expanded before the single-arg match")
                }
            };
            args.push(arg);
        }
        // Output expansion: the builder / (acc, fold) cross just before the
        // error callback.
        args.extend(unfold_call_args.iter().cloned());
        // Every extern takes a trailing error callback. The wrapper passes a
        // **capture** (`__cap`) that records `(je, ze…)` and sets a flag — no
        // throw on the Rust upcall. The wrapper calls the user's `onError` after
        // the native call returns (see the body below).
        args.push("__cap".to_string());
        let mut call = format!(
            "{}.{jni_call}({})",
            ext.jni_native_class_name(),
            args.join(", ")
        );
        if let Some(p) = &projection {
            // Fold the wrap through the projection strategy. The wrap class is
            // the projection leaf's typed short name (Handle's typed-handle
            // class or value-class wrapper). The sentinel is the Kotlin
            // null-representation literal for the leaf wire — used only by
            // the `Niche+primitive` arm of `fold_projection_wrap`.
            let leaf_fqn = ext.kotlin_fqn(&p.leaf_key).unwrap_or(&p.leaf_key);
            let short = leaf_fqn.rsplit('.').next().unwrap_or(leaf_fqn).to_string();
            let sentinel = projection_leaf_sentinel(p);
            call = fold_projection_wrap(&p.strategy, &call, &short, sentinel.as_deref());
        } else if is_enum_return {
            call = format!("{kt_return}.fromInt({call})");
        } else if unfold.is_some() && !is_convert {
            // Callback delivery: the extern returns the builder's erased `Any?`;
            // cast to the shape type (`R` / `R?` / `List<R>`). The builder always
            // produces `R`, so the unchecked cast is sound — suppressed below.
            call = format!("({call} as {kt_return})");
        }
        // Return delivery (`convert_output`): the extern returns the real typed
        // wire; the projection wrap above (if any) already produced the value
        // class / handle — no cast needed.
        call
    };

    let body_expr = build_call();

    // Collect the opaque-handle params so we can scaffold pointer-ordered
    // synchronized blocks around them.
    struct Opaque {
        /// Kotlin param name (e.g. `"b"`).
        name: String,
        /// Object to synchronize on and read the pointer from (`<name>`).
        target: String,
        /// Statement that nulls the pointer slot after consume
        /// (`"<target>.ptr = 0L"`), or `None` for borrow modes.
        consume_null: Option<String>,
        /// `true` for `Option<&T>` — nullable param, branches before lock.
        nullable: bool,
    }
    let opaques: Vec<Opaque> = params
        .iter()
        .filter_map(|p| {
            let (target, consume_null, nullable) = match p.mode {
                ParamMode::Borrow => (p.kt_name.clone(), None, false),
                ParamMode::Consume => (
                    p.kt_name.clone(),
                    Some(format!("{}.ptr = 0L", p.kt_name)),
                    false,
                ),
                ParamMode::BorrowNullable => (p.kt_name.clone(), None, true),
                // Nullable consume: null the slot only when present (null-safe).
                ParamMode::ConsumeNullable => (
                    p.kt_name.clone(),
                    Some(format!("{n}?.let {{ it.ptr = 0L }}", n = p.kt_name)),
                    true,
                ),
                _ => return None,
            };
            Some(Opaque {
                name: p.kt_name.clone(),
                target,
                consume_null,
                nullable,
            })
        })
        .collect();

    let is_unit = kt_return.is_empty();

    // Error callback `onError: (je: String?, ze…) -> R`. `je` (binding message)
    // is fixed; the `ze` params are the fn's `Result<_, E>` domain error
    // converted/deconstructed (from `error_plans`). The wrapper passes a capture
    // to the extern, then — after the native call — calls `onError(je, ze…)` and
    // returns its `R` if a failure was recorded (no throw on the Rust upcall).
    let r_ty = if is_unit { "Unit".to_string() } else { kt_return.clone() };
    let error_plan = registry.error_plans.get(&f.sig.ident);
    // Per ze leaf: (param name, public Kotlin type, default literal for a
    // binding error). Names derive from the error plan's accessor paths
    // (`z_error_message` on `&ZError` → `message`).
    let ze_info: Vec<(String, String, String)> = error_plan
        .map(|p| {
            let mut names = plan_leaf_names(registry, p);
            dedup_kt_param_names(&mut names);
            names
                .into_iter()
                .zip(p.leaves.iter())
                .map(|(name, leaf)| {
                    let out_ty = &leaf.out_ty;
                    let kt = if ext.is_kotlin_enum(&enum_probe_type(out_ty)) {
                        "Int".to_string()
                    } else {
                        let rt: syn::ReturnType = syn::parse_quote!(-> #out_ty);
                        classify_return(ext, &rt, registry, imports)
                            .map(|(k, _)| k)
                            .unwrap_or_else(|| "Any".to_string())
                    };
                    let default = kt_value_default(&kt);
                    (name, kt, default)
                })
                .collect()
        })
        .unwrap_or_default();
    let n_ze = ze_info.len();
    // Public `onError` param list: the fixed binding-error message `je`, then
    // each named ze leaf (non-null).
    let onerr_params = std::iter::once("je: String?".to_string())
        .chain(ze_info.iter().map(|(name, kt, _)| format!("{name}: {kt}")))
        .collect::<Vec<_>>()
        .join(", ");
    // Default handler: throws `ZException(je ?: ze0)` so a caller that doesn't
    // supply a handler still gets an exception (overridable per call). The lambda
    // params are named `__de_je, __de_z0, …` to match the arity.
    let default_lambda = {
        let lam_params = std::iter::once("__de_je".to_string())
            .chain((0..n_ze).map(|i| format!("__de_z{i}")))
            .collect::<Vec<_>>()
            .join(", ");
        let thrown = if n_ze >= 1 {
            "__de_je ?: __de_z0".to_string()
        } else {
            "__de_je".to_string()
        };
        // For a non-String first ze, fall back to `je` only (the throw takes a
        // `String?`); `__de_z0` is `String` only when the leaf is String.
        let thrown = if n_ze >= 1 && ze_info[0].1 == "String" {
            thrown
        } else {
            "__de_je".to_string()
        };
        format!("{{ {lam_params} -> throw ZException({thrown}) }}")
    };
    let onerr_param = format!("onError: ({onerr_params}) -> {r_ty} = {default_lambda}");
    // The je/ze argument list to call the user's `onError`, coalescing each
    // captured (nullable) ze with its default (a binding error leaves ze null).
    let onerr_call_args = std::iter::once("__cap_je".to_string())
        .chain(
            (0..n_ze).map(|i| {
                let (_, _, def) = &ze_info[i];
                format!("(__cap_ze{i} ?: {def})")
            }),
        )
        .collect::<Vec<_>>()
        .join(", ");
    // Default-ze args for a synchronous (pre-call) closed-handle guard, which
    // calls `onError` directly.
    let onerr_guard_args = std::iter::once("\"Operation on a closed native handle.\"".to_string())
        .chain(ze_info.iter().map(|(_, _, def)| def.clone()))
        .collect::<Vec<_>>()
        .join(", ");
    // Pre-lock closed-handle guards: a racy-but-safe `ptr == 0L` check before the
    // lock, returning `onError(...)` (function-level return; no throw).
    let mut prelock_guards = String::new();
    for o in &opaques {
        let cond = if o.nullable {
            format!("{n} != null && {t}.ptr == 0L", n = o.name, t = o.target)
        } else {
            format!("{t}.ptr == 0L", t = o.target)
        };
        if is_unit {
            prelock_guards.push_str(&format!("if ({cond}) {{ onError({onerr_guard_args}); return }}\n"));
        } else {
            prelock_guards.push_str(&format!("if ({cond}) return onError({onerr_guard_args})\n"));
        }
    }

    // Build `value_expr`: the (projection-wrapped) JNINative call, wrapped in
    // a consume `try/finally` when any handle is consumed.
    let consume_stmts: Vec<&str> = opaques
        .iter()
        .filter_map(|o| o.consume_null.as_deref())
        .collect();
    let value_expr = if consume_stmts.is_empty() {
        body_expr.clone()
    } else {
        format!(
            "try {{\n{body_expr}\n}} finally {{\n{}\n}}",
            consume_stmts.join("\n")
        )
    };

    // `core_expr`: a single Kotlin **expression** evaluating to the call's
    // result. Handle params contribute pointer-binding statements and a
    // deadlock-safe `withSortedHandleLocks` acquisition; the whole thing is
    // expression-shaped (via `run { … }` where statements are needed) so the
    // caller can bind it to `__ret`, rethrow a captured sink error, then
    // return.
    // Under-lock pointer reads. The closed-handle check is done pre-lock
    // (`prelock_guards`, → `onError`); these just bind the ptr the call passes.
    let mut ptr_binds = String::new();
    for o in &opaques {
        if o.nullable {
            ptr_binds.push_str(&format!("val {n}_ptr = {t}?.ptr ?: 0L\n", n = o.name, t = o.target));
        } else {
            ptr_binds.push_str(&format!("val {n}_ptr = {t}.ptr\n", n = o.name, t = o.target));
        }
    }

    let core_expr: String = if opaques.is_empty() {
        // No handles — the call expression stands alone.
        value_expr
    } else if !ext.emit_handle_locks {
        // Lock-free mode: ptr binds then the value, wrapped as an expression.
        format!("run {{\n{ptr_binds}{value_expr}\n}}")
    } else {
        // Fast path: a statically-known, small (1–3), all-non-null handle set.
        // Pass the handles positionally to the allocation-free fixed-arity
        // `withSortedHandleLocks` overload. Otherwise build a `List` and use
        // the recursive overload.
        let fixed_arity =
            !opaques.iter().any(|o| o.nullable) && (1..=3).contains(&opaques.len());
        if !ext.package.is_empty() {
            imports.insert(format!("{}.withSortedHandleLocks", ext.package));
            if !fixed_arity {
                imports.insert(format!("{}.NativeHandle", ext.package));
            }
        }
        if fixed_arity {
            let targets = opaques
                .iter()
                .map(|o| o.target.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            format!("withSortedHandleLocks({targets}) {{\n{ptr_binds}{value_expr}\n}}")
        } else {
            let mut adds = String::new();
            for o in &opaques {
                if o.nullable {
                    adds.push_str(&format!("{n}?.let {{ __locks.add(it) }}\n", n = o.name));
                } else {
                    adds.push_str(&format!("__locks.add({t})\n", t = o.target));
                }
            }
            format!(
                "run {{\nval __locks = ArrayList<NativeHandle>()\n{adds}withSortedHandleLocks(__locks) {{\n{ptr_binds}{value_expr}\n}}\n}}"
            )
        }
    };

    // The `onError` default throws the framework `ZException` (in `NativeHandle.kt`).
    if !ext.package.is_empty() {
        imports.insert(format!("{}.ZException", ext.package));
    }

    let mut out = String::new();
    let mut param_list: Vec<String> = params
        .iter()
        .map(|p| format!("{}: {}", p.kt_name, p.kt_type))
        .collect();
    // The error callback. When an output-expansion builder/fold lambda exists, it
    // must remain the **trailing** lambda (Kotlin trailing-lambda call syntax), so
    // `onError` (which carries a default) is placed *before* it — but *after* any
    // non-lambda `builder_lead` (`acc: A`), which is passed positionally. Without
    // a builder lambda, `onError` is the last param.
    if let Some(bp) = &builder_param {
        if let Some(lead) = &builder_lead {
            param_list.push(lead.clone());
        }
        param_list.push(onerr_param);
        param_list.push(bp.clone());
        let _ = writeln!(out, "@Suppress(\"UNCHECKED_CAST\")");
    } else {
        param_list.push(onerr_param);
    }
    let _ = write!(out, "public fun {generic}{kt_name}({})", param_list.join(", "));
    if !kt_return.is_empty() {
        let _ = write!(out, ": {kt_return}");
    }
    // No throw from the binding: the wrapper installs a **capture** the extern
    // invokes on `Err` (recording `(je, ze…)`), then — after the native call —
    // calls the user's `onError` and returns its `R`. A pre-lock closed-handle
    // guard short-circuits straight to `onError` (it can't reach the capture).
    let body: String = {
        let mut b = String::new();
        b.push_str(&prelock_guards);
        b.push_str("var __cap_failed = false\n");
        b.push_str("var __cap_je: String? = null\n");
        for i in 0..n_ze {
            let (_, kt, _) = &ze_info[i];
            b.push_str(&format!("var __cap_ze{i}: {kt}? = null\n"));
        }
        // The capture lambda: arity `1 + n_ze`, matching the extern's invoke.
        let cap_params = std::iter::once("__je: String?".to_string())
            .chain((0..n_ze).map(|i| {
                let (_, kt, _) = &ze_info[i];
                format!("__ze{i}: {kt}?")
            }))
            .collect::<Vec<_>>()
            .join(", ");
        let mut cap_body = String::from("__cap_failed = true; __cap_je = __je");
        for i in 0..n_ze {
            cap_body.push_str(&format!("; __cap_ze{i} = __ze{i}"));
        }
        b.push_str(&format!("val __cap = {{ {cap_params} -> {cap_body} }}\n"));
        if is_unit {
            b.push_str(&format!("{core_expr}\n"));
            b.push_str(&format!("if (__cap_failed) return onError({onerr_call_args})\n"));
        } else {
            b.push_str(&format!("val __ret = {core_expr}\n"));
            b.push_str(&format!("if (__cap_failed) return onError({onerr_call_args})\n"));
            b.push_str("return __ret\n");
        }
        b
    };
    let _ = writeln!(out, " {{");
    for line in body.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            let _ = writeln!(out, "    {line}");
        }
    }
    let _ = writeln!(out, "}}");
    Some(out)
}

/// The Kotlin typing of one delivered lambda leaf: `(builder_kt, wire_kt,
/// wrap, is_value_blob)` — the type the *user's* lambda sees, the type the
/// extern delivers, and the expression rebuilding the former from the latter
/// (`pk` is the adapter's parameter name; passthrough unless the leaf is a
/// `value_blob`, whose `@JvmInline value class` can't be built Rust-side).
/// Shared by the unfold builder/fold lambda and the callback lambda params.
fn unfold_leaf_kt(
    ext: &JniGen,
    registry: &Registry<KotlinMeta>,
    out_ty: &syn::Type,
    nullable: bool,
    pk: &str,
    imports: &mut BTreeSet<String>,
) -> Option<(String, String, String, bool)> {
    let proj = registry
        .output_entry(out_ty)
        .and_then(|e| e.metadata.projection.clone());
    let is_vb = proj
        .as_ref()
        .map(|p| p.kind == crate::api::lang::jnigen::jni::ProjectionKind::ValueBlob)
        .unwrap_or(false);
    // builder_kt: enum → Int; otherwise the normal classified type
    // (handle class / value class / String / ByteArray / Long …).
    let mut builder_kt = if ext.is_kotlin_enum(&enum_probe_type(out_ty)) {
        "Int".to_string()
    } else {
        let rt: syn::ReturnType = syn::parse_quote!(-> #out_ty);
        classify_return(ext, &rt, registry, imports)?.0
    };
    let (mut wire_kt, wrap) = if is_vb {
        let p = proj.as_ref().unwrap();
        let short = builder_kt.clone();
        let sentinel = projection_leaf_sentinel(p);
        (
            projection_wire_return(p),
            fold_projection_wrap(&p.strategy, pk, &short, sentinel.as_deref()),
        )
    } else {
        (builder_kt.clone(), pk.to_string())
    };
    if nullable {
        builder_kt.push('?');
        wire_kt.push('?');
    }
    Some((builder_kt, wire_kt, wrap, is_vb))
}

/// Stripped form of a deconstructor-record accessor ident relative to its
/// receiver type: `z_sample_key_expr` on `&ZSample` → `key_expr`;
/// `z_keyexpr_as_str` on `&ZKeyExpr` → `as_str`. The comparison is
/// normalized — lowercased with underscores removed — so irregular snake
/// forms (`z_keyexpr_` vs the type `ZKeyExpr`) still match. Falls back to
/// stripping a bare `z_` prefix, then to the full ident.
pub(crate) fn strip_receiver_prefix(registry: &Registry<KotlinMeta>, acc: &syn::Ident) -> String {
    let fn_str = acc.to_string();
    let receiver_short = registry.functions.get(acc).and_then(|(f, _)| {
        let ty = f.sig.inputs.iter().find_map(|i| match i {
            syn::FnArg::Typed(pt) => Some((*pt.ty).clone()),
            _ => None,
        })?;
        let ty = match ty {
            syn::Type::Reference(r) => (*r.elem).clone(),
            other => other,
        };
        if let syn::Type::Path(tp) = &ty {
            tp.path.segments.last().map(|s| s.ident.to_string())
        } else {
            None
        }
    });
    if let Some(short) = receiver_short {
        let norm_ty: String = short.to_lowercase().replace('_', "");
        let norm_fn: String = fn_str.replace('_', "").to_lowercase();
        if !norm_ty.is_empty() && norm_fn.starts_with(&norm_ty) {
            // Cut `norm_ty.len()` alphanumeric chars off the original ident
            // (underscores don't count), then trim separator underscores.
            let mut consumed = 0usize;
            let mut idx = fn_str.len();
            for (i, c) in fn_str.char_indices() {
                if consumed == norm_ty.len() {
                    idx = i;
                    break;
                }
                if c != '_' {
                    consumed += 1;
                }
            }
            let rest = fn_str[idx..].trim_start_matches('_');
            if !rest.is_empty() {
                return rest.to_string();
            }
        }
    }
    fn_str.strip_prefix("z_").unwrap_or(&fn_str).to_string()
}

/// Derived Kotlin parameter names for a plan's delivered leaves, in leaf
/// order: the camelCased join of every path segment stripped of its receiver
/// type ([`strip_receiver_prefix`]) — fully mechanical, and unique because
/// accessor paths are (`keyExpr`, `keyExprAsStr`, `payloadToBytes`, …). The
/// root identity leaf (empty path) is `handle`. Names are keyword-escaped via
/// [`kt_param_name`]; run [`dedup_kt_param_names`] over the final per-lambda
/// list.
fn plan_leaf_names(
    registry: &Registry<KotlinMeta>,
    plan: &crate::api::core::unfold::UnfoldPlan,
) -> Vec<String> {
    plan.leaves
        .iter()
        .map(|leaf| {
            if leaf.path.is_empty() {
                "handle".to_string()
            } else {
                let joined = leaf
                    .path
                    .iter()
                    .map(|a| strip_receiver_prefix(registry, a))
                    .collect::<Vec<_>>()
                    .join("_");
                kt_param_name(&joined)
            }
        })
        .collect()
}

/// Make one lambda's parameter-name list unique: a duplicate gets a numeric
/// suffix (`name2`, `name3`, …). Names in a Kotlin function type are purely
/// documentational but must still be distinct identifiers.
fn dedup_kt_param_names(names: &mut [String]) {
    let mut seen: HashSet<String> = HashSet::new();
    for n in names.iter_mut() {
        if !seen.insert(n.clone()) {
            let mut k = 2;
            while !seen.insert(format!("{n}{k}")) {
                k += 1;
            }
            *n = format!("{n}{k}");
        }
    }
}

/// Lambda parameter name for a whole-value (plan-less) callback arg: the
/// decapitalized bare type short (`ZQuery` → `zQuery`), peeling a `&` /
/// `Option<…>` layer; `arg{i}` for non-path shapes.
fn whole_value_name(ty: &syn::Type, i: usize) -> String {
    let mut t = ty.clone();
    if let syn::Type::Reference(r) = &t {
        t = (*r.elem).clone();
    }
    if let syn::Type::Path(tp) = &t {
        if let Some(last) = tp.path.segments.last() {
            if last.ident == "Option" {
                if let syn::PathArguments::AngleBracketed(ab) = &last.arguments {
                    if let Some(syn::GenericArgument::Type(inner)) = ab.args.first() {
                        t = inner.clone();
                    }
                }
            }
        }
    }
    if let syn::Type::Path(tp) = &t {
        if let Some(last) = tp.path.segments.last() {
            let s = last.ident.to_string();
            let mut cs = s.chars();
            if let Some(f) = cs.next() {
                return kt_param_name(&format!("{}{}", f.to_lowercase(), cs.as_str()));
            }
        }
    }
    format!("arg{i}")
}

/// A Kotlin default-value literal for a (non-null) error `ze` leaf type, used
/// when a **binding** error leaves the `ze` null (the value is ignored — the
/// caller uses `je`). Covers the realistic leaf types; an unknown type falls
/// back to a non-null-asserting `null!!` (never reached, since `je` is set).
fn kt_value_default(kt: &str) -> String {
    match kt {
        "String" => "\"\"".to_string(),
        "Long" => "0L".to_string(),
        "Int" => "0".to_string(),
        "Short" => "0".to_string(),
        "Byte" => "0".to_string(),
        "Boolean" => "false".to_string(),
        "Double" => "0.0".to_string(),
        "Float" => "0.0f".to_string(),
        "Char" => "'\\u0000'".to_string(),
        "ByteArray" => "ByteArray(0)".to_string(),
        _ => "null!!".to_string(),
    }
}

/// Fall-back Kotlin type derived directly from the JNI wire type.
/// Returns the **non-nullable** Kotlin base name — the use site adds
/// a `?` suffix when the entry's Rust type is `Option<…>` (via
/// [`is_option_type`]), so this helper must not double up.
pub(crate) fn kotlin_for_wire(wire: &syn::Type) -> Option<String> {
    if let syn::Type::Path(tp) = wire {
        if let Some(last) = tp.path.segments.last() {
            let name = last.ident.to_string();
            let kt = match name.as_str() {
                "jboolean" => "Boolean",
                "jbyte" => "Byte",
                "jchar" => "Char",
                "jshort" => "Short",
                "jint" => "Int",
                "jlong" => "Long",
                "jfloat" => "Float",
                "jdouble" => "Double",
                "JString" | "jstring" => "String",
                "JByteArray" | "jbyteArray" => "ByteArray",
                "JObject" | "jobject" => "Any",
                "JClass" => "Any",
                _ => return None,
            };
            return Some(kt.to_string());
        }
    }
    None
}

/// Returns `(kt_return, projection)` where:
/// * `kt_return` is the declared Kotlin return type written in the
///   wrapper's signature (empty for `Unit`).
/// * `projection` is `Some(Projection)` when the return is a Kotlin newtype
///   (opaque handle or value class) reached through 0+ wrappers. The
///   wrapper body uses it to fold the wrap call (`W(x)` for `Direct`,
///   `?.let { W(it) }` for `Nullable`, `.map { W(it) }` for `Iterable`)
///   and pick the JNI extern's wire return (`Long` for `Handle`,
///   the inner wire's Kotlin name for `ValueClass`). `None` for plain
///   non-projection returns.
pub(crate) fn classify_return(
    ext: &JniGen,
    output: &syn::ReturnType,
    registry: &Registry<KotlinMeta>,
    imports: &mut BTreeSet<String>,
) -> Option<(
    String,
    Option<crate::api::lang::jnigen::jni::Projection>,
)> {
    let ty = match output {
        syn::ReturnType::Default => return Some((String::new(), None)),
        syn::ReturnType::Type(_, t) => &**t,
    };
    let outer_meta = registry.output_entry(ty).map(|e| e.metadata.clone());
    // Unit returns (incl. `ZResult<()>`, whose inner identity rides
    // `value_rust_key`) declare no Kotlin return type.
    let inner_canon = outer_meta
        .as_ref()
        .and_then(|m| m.value_rust_key.clone())
        .unwrap_or_else(|| ty.to_token_stream().to_string());
    let inner: syn::Type = syn::parse_str(&inner_canon).unwrap_or_else(|_| ty.clone());
    if crate::api::lang::jnigen::util::is_unit(&inner) {
        return Some((String::new(), None));
    }
    // Projection return (opaque handle or value class): read the folded
    // `Projection` the type-unfolding mechanism propagated onto this return
    // type's converter metadata — one source of truth, no shape-specific
    // peeling. The declared return type is the concrete projection class
    // folded through `Nullable`/`Iterable`; callers fold the wrap and pick
    // the wire return based on `kind`.
    if let Some(h) = outer_meta.as_ref().and_then(|m| m.projection.clone()) {
        let fqn = ext
            .kotlin_fqn(&h.leaf_key)
            .map(|v| v.to_string())
            .unwrap_or_else(|| {
                panic!(
                    "classify_return: projection return type `{}` has no Kotlin FQN registered \
                     — every opaque/value class must be declared via `JniGen::ptr_class(...)` \
                     / `JniGen::value_class(...)`.",
                    h.leaf_key
                )
            });
        let short = register_fqn(&fqn, imports);
        return Some((render_handle_type(&h.strategy, &short), Some(h)));
    }
    // Non-opaque: read the Kotlin name straight off the resolved
    // output entry's metadata — the rank-N handler propagates
    // `ZResult<T>` / `Option<T>` / `Vec<T>` derivations alongside the
    // wire, so no peel-and-fallback chain is needed at the use site.
    if let Some(out_entry) = registry.output_entry(ty) {
        if let Some(kt) = out_entry.metadata.kotlin_name.clone() {
            return Some((register_fqn(&kt, imports), None));
        }
    }
    None
}

/// Returns `true` when the function's return type resolves to a type registered
/// via [`JniGen::enum_class`]. Enum returns cross the JNI wire as `jint` (Kotlin
/// `Int`); the public wrapper must call `EnumType.fromInt(Int)` to convert back.
pub(crate) fn return_is_kotlin_enum(
    ext: &JniGen,
    output: &syn::ReturnType,
    registry: &Registry<KotlinMeta>,
) -> bool {
    let ty = match output {
        syn::ReturnType::Default => return false,
        syn::ReturnType::Type(_, t) => &**t,
    };
    let outer_meta = registry.output_entry(ty).map(|e| e.metadata.clone());
    let inner_canon = outer_meta
        .as_ref()
        .and_then(|m| m.value_rust_key.clone())
        .unwrap_or_else(|| ty.to_token_stream().to_string());
    let inner: syn::Type = syn::parse_str(&inner_canon).unwrap_or_else(|_| ty.clone());
    ext.is_kotlin_enum(&inner)
}

pub(crate) fn kt_snake_to_camel(s: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in s.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.push(c.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Camel-case a Rust param ident into a valid Kotlin parameter name. Kotlin
/// **hard keywords** can't be used as identifiers (not even back-ticked), so a
/// collision is escaped by appending `_`. Param names don't affect JNI linkage
/// (only the function name + JVM signature do), so renaming is always safe.
pub(crate) fn kt_param_name(rust_ident: &str) -> String {
    let camel = kt_snake_to_camel(rust_ident);
    const HARD_KEYWORDS: &[&str] = &[
        "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
        "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
        "true", "try", "typealias", "typeof", "val", "var", "when", "while",
    ];
    if HARD_KEYWORDS.contains(&camel.as_str()) {
        format!("{camel}_")
    } else {
        camel
    }
}
