name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.75.0, stable]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust ${{ matrix.rust }}
      run: |
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo build
    - name: Run tests
      run: 
        cargo test
        cargo test --all --all-features
