name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.75.0, stable]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust ${{ matrix.rust }}
      run: |
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}

    - name: Install Rust toolchain
      run: rustup component add rustfmt clippy

    - name: Run clippy without default features
      run: cargo clippy --all-targets --no-default-features --all-features -- --deny warnings

    - name: Run rustfmt
      run: cargo fmt --check -- --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate"

    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        cargo test
        cargo test --all --all-features
